### ISSUE TITLE
Suggestion list doesn't close on mobile after suggestion click/selection

### ISSUE THREAD

**Issue by matthiascw** [KazanExpress/vue-simple-suggest#100]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
When I select a suggestion on mobile the suggestion-list doesn't close. The show-list event is immediately called after the hide-list event.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Open the projects example (https://kazanexpress.github.io/vue-simple-suggest/) and toggle chrome's device toolbar. In the event log you can see that the show-list event is immediately fired after the hide-list event when you select a suggestion in mobile mode.

## **What is the expected behavior?**
The same behavior as on Desktop. The suggestion-list should disappear on selection so the show-list event should not be fired again on mobile.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.17
  - Vue-simple-suggest version: 1.8.3
  - Browser: [Chrome 71.0.3578.98 | Mobile Chrome 71.0.3578.99]
  - Language: [ES6/7]

Listening to the select or selection-click event and trying to hide the list doesn't work. It seems to fire the select and show-list event again on mobile.

**Comment by brickgale** [comment]
+1

**Comment by brickgale** [comment]
i fixed mine with a "hack", it isn't good but it fixed the issue.
```
this.$nextTick(() => {
     this.$refs['suggest-email'].hideList()
})
```
added this code on a function which handles the event `hide-list`.

**Comment by jalerson** [comment]
+1 for this issue

Thanks @brickgale for the hack 👍

**Comment by Raiondesu** [comment]
@brickgale, wow, a very nice workaround!

As I now have more time for resolving these issues, I will look for the actual solution to this problem.

I'll keep this issue open for task-management purposes.

**Comment by Raiondesu** [comment]
A PR would be highly welcome, though.
