### ISSUE TITLE
 Get Value from the array object and put it in v-model 

### ISSUE THREAD

**Issue by misbahartra** [KazanExpress/vue-simple-suggest#101]
I want to take the value 01
from data . with display text.
and i want the city_code : 1
can anyone help? .
=============================
CODE 
`
<vue-simple-suggest 
                                            v-model="chosen"
                                            value-attribute="value"
                                            display-attribute="text"
                                            :list="this.kota"
                                            :filter-by-query="true"
                                            mode="select"
                                            @suggestion-click="selectCity" >
                                        <input placeholder="Kode Kota" type="search">
                                        </vue-simple-suggest>`

=============================
DATA
```
[  
   {  
      "text":"BELAWAN-MEDAN",
      "value":"1"
   },
   {  
      "text":"PEMATANG SIANTAR",
      "value":"2"
   }
]
```

**Comment by juliengk** [comment]
same here

**Comment by Raiondesu** [comment]
Hello, @misbahartra, @juliengk. Could you, please, specify what exactly is your situation?

You can add city code to your objects, and set it as a value attribute, if this is what you want.

I'll close this issue, until @misbahartra reformats it appropriately.
