### ISSUE TITLE
option is not clickable

### ISSUE THREAD

**Issue by saiqulhaq** [KazanExpress/vue-simple-suggest#105]
I'm submitting a bug report

## **What is the current behavior?**

first option is not clickable, another options is fine

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

open http://www.hungryhub.com/en
and in the search form, please fill 'Audrey' as keyword, you will find that first option is not clickable

## **What is the expected behavior?**

all options should be clickable

### How are you importing Vue-simple-suggest?

ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.8.3
  - Browser: Chrome Ubuntu
  - Language: ES6

**Comment by Raiondesu** [comment]
Hello, @saiqulhaq.

We determined that the issue is not present on Windows and Mac. We'll try to reproduce your issue using Ubuntu and report here later.

**Comment by saiqulhaq** [comment]
first option

![Screenshot 2019-03-31 20:59:16](https://user-images.githubusercontent.com/1275215/55290026-13c23400-53f8-11e9-9e25-16e1313ad568.png)


second option

![Screenshot 2019-03-31 20:59:29](https://user-images.githubusercontent.com/1275215/55290028-1755bb00-53f8-11e9-9764-03b1e45d0d9a.png)


as you could see
the second one has 'alt' text
but it's missing on first option and not clickable

**Comment by Raiondesu** [comment]
@saiqulhaq, unfortunately, we are unable to reproduce this. 😞 

Is it possible for you to create an example on jsfiddle.com that reproduces the problem?

**Comment by saiqulhaq** [comment]
This is my custom VueSimpleSuggest template

```
<VueSimpleSuggest
    @select="selectSuggestion"
    :list="getSuggestion"
    @request-failed="onRequestFailed"
    :styles="{ vueSimpleSuggest: mainWrapperClass }"
    :debounce="200"
    v-model="keyword"
    :prevent-submit="false"
    @input="onChangeKeyword"
  >
    <div :class="wrapperClass">
      <span :class="iconClass">
        <input
          aria-label="name"
          type="text"
          :value="keyword"
          :class="inputClass"
          :placeholder="$t('search')"
        >
      </span>
    </div>
    <template slot="misc-item-above" slot-scope="{ suggestions }" v-if="suggestions.length > 0">
      <div v-if="suggestions.length > 0" class="pa2">
        <span>{{ $t('doYouMean') }}</span>
      </div>
    </template>

    <div slot="suggestion-item" slot-scope="scope" :title="scope.suggestion.title">
      <div
        class="pointer pa1 mv1 ba b--black-30 bg-white z-999 br2 flex justify-between items-center"
      >
        <span class="f7" v-html="scope.suggestion.title"></span>
        <i class="icon-right-open"></i>
      </div>
    </div>

    <div class="pa2" slot="misc-item-below" v-if="isLoading">
      <i class="icon-spinner animate-spin"></i>
      <span>Loading...</span>
    </div>
  </VueSimpleSuggest>
```


[Untitled.mov.zip](https://github.com/KazanExpress/vue-simple-suggest/files/3076991/Untitled.mov.zip)

**Comment by kaskar2008** [comment]
@saiqulhaq I guess I got it. You have a button, that partly covers your suggestion list. Try to set `z-index` grater than that button.
![image](https://user-images.githubusercontent.com/6456858/56131497-4475a200-5f90-11e9-99c6-354208cd217c.png)

**Comment by saiqulhaq** [comment]
@kaskar2008 you are genius. thank you very much
