### ISSUE TITLE
Suggestion list is not closing with Bootstrap-Vue input

### ISSUE THREAD

**Issue by andriasmelianus** [KazanExpress/vue-simple-suggest#107]
## **I'm submitting a ...**
  - [x] support request

## **What is the current behavior?**
The component produces an error when `blur` event fired.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I am using `<b-form-input />` from Bootstrap-Vue to replace default input control.
Whenever I lost focus of this component, it produces an error in the console, and the suggestion list is not closed.
![image](https://user-images.githubusercontent.com/7449543/55146226-bb303400-5176-11e9-9e3a-fe78775c6543.png)

## **What is the expected behavior?**
Suggestion list closed when I move/focus to another input in the form.
I have tried `@blur.prevent` and `@blur.stop` either in `<vue-simple-suggest />` or `<b-form-input />`, but the error remain and suggestion list is not closing.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.22
  - Vue-simple-suggest version: 1.8.3
  - Browser: Chromium 73
  - Language: ES5

**Comment by Raiondesu** [comment]
Hello, @andriasmelianus. This is a very concerning issue for us. Can you, please, provide a repo or jsfiddle that reproduces this issue?

**Comment by Raiondesu** [comment]
@andriasmelianus, also check the [custom input component caveats](https://github.com/KazanExpress/vue-simple-suggest#custom-input) section in our readme. It is very possible, that `<b-form-input>` does not emit a `focus` event properly.

**Comment by andriasmelianus** [comment]
Hi @Raiondesu, sorry i am unable to provide the jsfiddle yet, due to very slow internet connection.
So, `<b-form-input>` is not compatible with the component? 
Or is there any way to emit a `focus` event properly?
I have tried this on `<b-form-input>`:
```
onInput: function(value){
  this.$emit('input', value)
},
onFocus: function(e){
  this.$emit('focus', e)
},
onBlur: function(e){
  this.$emit('blur', e)
},
```
But the error still there.
Thanks

**Comment by Raiondesu** [comment]
@andriasmelianus, unfortunately, your example does not fix the problem.

What you need to do is wrap `<b-form-input>` in your own component that emits correct events.
Please, refer to the [Vue documentation](https://vuejs.org/v2/api/#extends) on the correct way of doing this.

You also can do the following:
```html
<template>
  <vue-simple-suggest mode="input"
                      value-attribute="name"
                      display-attribute="name" ref="suggest"

                      :list="getAddresses"
                      :remove-list="false"
                      :debounce="300"
                      :filter-by-query="true">
    <b-form-input :value="value"
                  :state="state" 
                  @blur="onBlur"

                  type="text"
                  autocomplete="off" 
                  placeholder="Ketikkan alamat"></b-form-input>

    <template slot="misc-item-above" slot-scope="{suggestions, query}">
      <div class="misc-item" v-show="!suggestions.length">
        <strong>{{ query }}</strong> akan ditambahkan di dalam database.
      </div>
    </template>

    <div slot="suggestion-item" slot-scope="{suggestion}">
      <span><i class="icon-location-pin" /> {{ suggestion.name }}</span><br>
      <small>Kode pos: {{ suggestion.postal_code }}</small>
    </div>
  </vue-simple-suggest>
</template>

<script>
import VueSimpleSuggest from 'vue-simple-suggest'
import 'vue-simple-suggest/dist/styles.css'
export default {
  name: 'Input',
  components: {
    VueSimpleSuggest
  },
  props: {
    state: {type: Boolean, default: true},
    value: {type: String}
  },
  data(){
    return {
      minCharToShow: 3,
    }
  },

  methods: {
    onBlur: function(e){
      this.$refs.suggest.isInFocus = true;
      this.$refs.suggest.onBlur(e);
    },
    getAddresses: function(keyword){
      let params = {keyword: keyword},
      vm = this,
      addresses = []

      if(keyword.length < this.minCharToShow){
        return addresses;
      }

      addresses = new Promise(function(resolve, reject){
        vm.$axios.get(vm.$store.getters.apiUrl('/address'), {params: params})
          .then(function(response){
            resolve(response.data.data)            
          })
          .catch(function(error){
            reject(error.response)
          })
      })

      return addresses
    }
  }
}
</script>
```

**Comment by Raiondesu** [comment]
@andriasmelianus, I'm closing the issue for maintenance purposes. Please, report here again if the issue persists.

**Comment by kngai** [comment]
I was experiencing this very similar issue using `"bootstrap-vue": "^2.0.0-rc.22"` with the `<b-input-form>` as my custom text input.

This was fixed by simply adding a `@focus` event handler.

```html
      <vue-simple-suggest
        ref="geolocationSuggest"
        :list="suggestGeoLocation"
        :debounce="250"
        @select="setSelectedLocation">
        <b-form-input
          value=""
          autocomplete="off"
          v-model="queryLocation"
          id="geolocation-search"
          type="search"
          placeholder="Search location"
          :class="validationClass"
          @focus="onFocus">
        </b-form-input>
        <div slot="suggestion-item" slot-scope="scope">
          <span v-html="boldenSuggestion(scope)"></span>
        </div>
      </vue-simple-suggest>
```

And in my `methods`:
```js
onFocus: function (evt) {
      this.$refs.geolocationSuggest.isInFocus = true
      this.$refs.geolocationSuggest.onFocus(evt)
    }
```

Hope that helps for anyone experiencing the same issue.
