### ISSUE TITLE
How to focus input by clicking on another button

### ISSUE THREAD

**Issue by robjbrain** [KazanExpress/vue-simple-suggest#110]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

When attempting to focus the input from another button, the input does not become focused.

Here is a JS Fiddle example: https://jsfiddle.net/xoy8La7k/

Here is an example component:

```
<template>
    <div>
        <div style="padding:10px;">
            <button type="button" @click="showSuggestForm">Show Form</button>
            <div ref="suggestForm" id="suggestForm">
                <vue-simple-suggest ref="suggestInput"></vue-simple-suggest>
            </div>
        </div>
        <div style="padding:10px;">
            <button type="button" @click="showBasicForm">Show Form</button>
            <div ref="basicForm" id="form">
                <input ref="basicInput" />
            </div>
        </div>
    </div>
</template>

<script>
    import VueSimpleSuggest from "vue-simple-suggest/lib/vue-simple-suggest";

    export default {
        components: {
            VueSimpleSuggest
        },
        methods: {
            showSuggestForm() {
                this.$refs.suggestForm.classList.add('show')

                // Returns an error
                // this.$refs.suggestInput.focus is not a function
                this.$refs.suggestInput.focus()

                // Found this example elsewhere but it doesn't work and i'm not sure if it's meant to
                this.$refs.suggestInput.$el.focus()
            },
            showBasicForm() {
                this.$refs.basicForm.classList.add('show')
                this.$refs.basicInput.focus()
            }
        },
    };
</script>
<style>
    #form, #suggestForm {
        display:none;
    }

    #form.show, #suggestForm.show {
        display:block;
    }
</style>
```

## **What is the current behavior?**

Focus does not work for the suggest input.

` this.$refs.suggestInput.focus()` returns the error "this.$refs.suggestInput.focus is not a function"

I found `this.$refs.suggestInput.$el.focus()` as an example when Googling but it doesn't seem to work either and i'm not sure if it's meant to or what this actually does.

## **What is the expected behavior?**

You should be able to call focus on the component and be able to type typing straight away not actually have to click on the component.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.22
  - Vue-simple-suggest version: 1.8.3
  - Browser: [Chrome ]
  - Language: [ES6]

**Comment by Raiondesu** [comment]
Hello, @robjbrain. :)

Nice to see you reporting here again.

You can force-focus the input using [ref data](https://github.com/KazanExpress/vue-simple-suggest#ref-data)'s `input` or `inputElement` properties, like so:
```js
this.$refs.suggestInput.input.focus();
// or:
this.$refs.suggestInput.inputElement.focus();
```

The difference here is that `input` references whatever input is currently passed to `vue-simple-suggest` - custom component or a vanilla HTML input, whereas `inputElement` **always** references the HTML `<input>` element, even if it's inside of a custom component.

So, for your exact case, I'd recommend using `this.$refs.suggestInput.inputElement.focus()`.

**Comment by Raiondesu** [comment]
Closing the issue for maintenance purposes.

@robjbrain , please, report here again if the solution does not work for you for some reason.
