### ISSUE TITLE
ID is returning with undefined whenever an object is passed into the suggestion-item slot

### ISSUE THREAD

**Issue by virtualbjorn** [KazanExpress/vue-simple-suggest#113]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
Whenever we use a second level child property the id is returning with undefined thus putting up warnings of duplicate keys

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```TS
suggestionItem = [{ name: 'suggestion-1', description: 'First' }, { name: 'suggestion-2', description: 'Second' }, { name: 'suggestion-3', description: 'Third' }]
```
```html
<vue-simple-suggest>
<div slot="suggestion-item" slot-scope="suggestionItem">
<div>{{ suggestionItem.suggestion.description }}</div>
</div>
</vue-simple-suggest>
```

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: typescript-vue 1.0.0
  - Vue-simple-suggest version: 1.8.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: TypeScript 2.7.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @virtualbjorn.

Are you sure you provided the necessary props `display-attribute` and `value-attribute`?

If yes, could you please replicate the issue on jsfiddle.net or an analagous resource?

**Comment by Raiondesu** [comment]
@virtualbjorn, actually, you gave us an idea for error reports.

**Comment by virtualbjorn** [comment]
I haven't yet used a library when using jsfiddle but I'll see what I can do. and replicate the issue there since I can't share the code here as it is an enterprise one.

**Comment by Raiondesu** [comment]
@virtualbjorn, have you tried to set `disaply-attribute` and `value-attribute` as shown in the example above?

**Comment by virtualbjorn** [comment]
Does value-attribute is the id for the suggestion item?

**Comment by Raiondesu** [comment]
Yes.

**Comment by Raiondesu** [comment]
I am closing the issue since this is not an issue with the component itself. Please, report here, if you fail to make your example work.

**Comment by virtualbjorn** [comment]
![image](https://user-images.githubusercontent.com/19782129/55502067-5432e380-567e-11e9-893d-212e37291fd1.png)

display-attribute and value-attribute doesn't work at all

**Comment by Raiondesu** [comment]
@virtualbjorn, can you, please, provide how exactly have you used `value-attribute` for your suggestions?
