### ISSUE TITLE
Event is not defined with nuxt.js

### ISSUE THREAD

**Issue by alexhyriavets** [KazanExpress/vue-simple-suggest#115]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
On the component's mount throws a runtime exception "event is not defined"
![image](https://user-images.githubusercontent.com/19614509/55496191-20889700-5647-11e9-98d7-64749b959056.png)

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
STR:
- create an empty nuxt app
- add vue-simple-suggest
- refresh the page

## **What is the expected behavior?**
It should work:)

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
 
  - Vue.js Version: 2.6.10
  - Vue-simple-suggest version: 1.9.2
  - Browser: [all]
  - Language: [all]

## **Other information**

Probably bug was created by fixing #92 . If revert these changes all works well:)

**Comment by Raiondesu** [comment]
Hello, @alexhyriavets.

This is indeed a bug and it will be fixed in the next patch.

**Comment by Raiondesu** [comment]
@all-contributors please add @alexhyriavets  for bug

**Comment by Raiondesu** [comment]
@alexhyriavets, here ya go.
