### ISSUE TITLE
tabindex should not be set on container div

### ISSUE THREAD

**Issue by behnoodk** [KazanExpress/vue-simple-suggest#118]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
When `tabindex` is provided on the component's props, it is set both on the container `div` and `input` element. With this behavior when user is moving through a form with tab key, the `div` gets focused first, then user needs to press the tab key one more time for the input to get the focus.

## **What is the expected behavior?**
`tabindex` should only be set on `input` and not the container `div`.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
To restore the default/standard behavior when user is navigating through a form with tab key.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.9.3

## Suggestion
This issue can be fixed very easily by setting `tabindex="-1"` on container `div` element. It is just a container and user does not need to interact with it in anyway.

As I understood by reading a few other issues, development time will be spent on version 2 of the component. If you approve of the suggested fix, I can make a PR.

Thank you for this awesome component.

**Comment by Raiondesu** [comment]
Hello, @behnoodk! Thank you for the compliment. 😊

Indeed, this is a bug. It can be fixed easily, though - we simply forgot to add `inheritAttrs: false` to component's definition. So it'll be fixed in the next patch. Hopefully, tonight. 😃

**Comment by Raiondesu** [comment]
@allcontributors[bot] please add @behnoodk for bug
