### ISSUE TITLE
Old promises are not invalidated when user types on

### ISSUE THREAD

**Issue by gregopet** [KazanExpress/vue-simple-suggest#123]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
When my `list` function returns a promise, the order in which the promises were triggered is not taken into account. An earlier promise may resolve slower than a later promise (due to the upstream server dealing with a heavy load, or network conditions, or whatever..) and when it does resolve, it overrides the correct response.

When the `list` function returns new promise, old promises should be cancelled/ignored or the user will end up with invalid suggestions.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I've created [a JSFiddle](https://jsfiddle.net/o8q1nfb9/1/). It always returns a single result (the entered text itself) after a random delay. Try typing a few words in there and the suggestion you end up with will almost certainly not be the final text, but rather an intermediate version.

## **What is the expected behavior?**

Old unresolved promises should be cancelled or disregarded.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [X] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
If you have several of these controls in the same page, tracking all the promises and cancelling them manually involves quite a lot of bookkeeping, it should be solved in the component itself I believe.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: all
  - Language: TypeScript,  ES6/7 (e.g. JS Fiddle)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @gregopet.

You have successfully described how promises work. And our component treats them as they are. Any custom behaviour is up to you.

Our component, however, has a [`debounce` prop](https://github.com/KazanExpress/vue-simple-suggest#props).
Please, refer to the documentation more carefully.

The problem you're currently experiencing is called "race condition". In this context, the most straight-forward way of solving it is **debouncing** the `list` function. If our own implementation does not suit your needs, many other solutions already exist for many cases, so you don't have to necessary reimplement this on your own ([examples](https://www.google.ru/search?q=js+debounce+promises+npm)).

**Comment by gregopet** [comment]
I know about debounce and it does not solve my problem.

Consider a city search control, backed by a database. The user may first type `HAM` after which a search promise is created. This search takes quite some time however because it matches many results. The user then completes the input so it now says `HAMBURG` and the search completes almost immediately, the user is presented with a few (correct) options. But after a couple of seconds, the correct list of options disappears and is replaced by one that also contains `Ham` and `Hamilton` because the initial search had _finally_ concluded.

The custom behavior of my promise to fetch data from my backend server is custom behavior. The UX experience of the user who types into a vue-simple-suggest component ought to be the concern of a UX component, however, especially since their ordering depends on the user's input.

I have a workaround for my code and it is simple: I keep a counter in my state and I increment & store its state in the promise's lambda. When the response comes back, I throw an exception if the current counter value does not match the value stored in the promise. 

I do have quite a few vue-simple-select elements on my page however and tracking all their states is cumbersome, plus I have to mix UI logic with my business logic which I would rather not have to do.

**Comment by gregopet** [comment]
Thank you for revisiting the issue, and also for the workaround. Unfortunately, if I apply the workaround similarly to that fiddle, component properties like `debounce`, `min-length`, `request-start`, `request-done` etc.. all stop working.

**Comment by kaskar2008** [comment]
@gregopet That's because it's a specific usecase and you should control the request all by yourself for now. Maybe I'll patch it today if I won't be too busy. Feel free to contribute tho 😉
