### ISSUE TITLE
Mode select not working. It keeps updating v-model

### ISSUE THREAD

**Issue by stripathix** [KazanExpress/vue-simple-suggest#125]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
I have vue-simple-suggest with mode="select". But it keeps updating v-model value due to some reason as I type. v-model also keeps updating.
```
  <vue-simple-suggest
        id="input-live"
        v-model="selectedItem"
        value-attribute="name"
        display-attribute="name"
        mode="select"
        @select="onSuggestSelect"
        :list="simpleSuggestionList">
        <input type="text">
      </vue-simple-suggest>
export default {
  components: {
    VueSimpleSuggest,
  },
  data() {
    return {
      selectedItem: null,
      selected: '',
    };
  },
  methods: {
    onSuggestSelect (suggest) {
        this.selected = suggest;
      },
    simpleSuggestionList() {
      return [
        {name: 'Afghanistan', code: 'AF'},
        {name: 'Åland Islands', code: 'AX'},
        {name: 'Albania', code: 'AL'},
        {name: 'Algeria', code: 'DZ'},
        {name: 'American Samoa', code: 'AS'},
        {name: 'AndorrA', code: 'AD'},
        {name: 'Angola', code: 'AO'},
        {name: 'Anguilla', code: 'AI'},
        {name: 'Antarctica', code: 'AQ'},
        {name: 'Antigua and Barbuda', code: 'AG'},
        {name: 'Argentina', code: 'AR'},
      ];
    },
  },
};
```

## **What is the expected behavior?**
v-model should not change if mode="select"

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.16
  - Vue-simple-suggest version: 1.9.5
  - Browser: all
  - Language:ES6

**Comment by Raiondesu** [comment]
Hello, @stripathix. :)

Thank you for the issue. We cannot, however, reproduce it.

Could you, please, provide at least a minimum reproduction playground/repo? Or, at least, if there are any console errors?

**Comment by stripathix** [comment]
Sure I will submit a reproduction repo.
Note I am trying to create a wrapper over this component using inheritAttrs, v-bind and v-on.

**Comment by stripathix** [comment]
Here is a sample repo to reproduce. Mode=select is updating v-model also. 

https://github.com/stripathix/vue-simple-suggest-mode-select

*Note: I have created a wrapper component using inheritAttr because I am adding this to a toolkit where I can add specific CSS and config some setting globally for wrapper component.

**Comment by stripathix** [comment]
Hey @Raiondesu did you got chance to look into the issue.

**Comment by Raiondesu** [comment]
@stripathix, we will have time to experiment with your repo tomorrow. Thank you very much for taking the time on reproducing the issue! 🙏

**Comment by stripathix** [comment]
Hi, @Raiondesu  did you got chance to look into the issue.  :)

**Comment by Raiondesu** [comment]
Hello, @stripathix. Unfortunately, we don't have the necessary time to fix this right now, as release schedules are really thight for our internal company projects.

In the mean-time, you can propose your solutions via a Pull Request. 😇\
We would be very glad, if you did.

**Comment by kaskar2008** [comment]
Hello @stripathix. As you can see from notifications on other of your issues I've got some free time to asnwer some open issues:) Finally xD

So sorry for taking it so long.

This bug is reproducible because you are wrapping our component with another component. YES you are forwarding events and bindings correctly. BUT! There is one thing we didn't account: you MUST describe the model yourself. Just add this to your component options and you are ready to go :)

```js
model: {
  prop: 'value',
  event: 'select'
}
```

You can read more about `model` in the [Vue.js documentation](https://vuejs.org/v2/api/#model). Hope this will help :)
