### ISSUE TITLE
Way to get autosuggestion list in viewport

### ISSUE THREAD

**Issue by stripathix** [KazanExpress/vue-simple-suggest#126]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the current behavior?**
If the input box is almost at the bottom edge of the screen or a container div and if the user starts typing then suggestions list is shown outside viewport and user will never know that there are suggestions below.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
This will happen in any sample because the suggestions list are not positioned dynamically.

## **What is the expected behavior?**
There can be 2 options
1) Suggestions list is positioned smartly depending on the view area. Something similar to the bootstrap dropdown. Ref (https://getbootstrap.com/docs/4.0/components/dropdowns/)

2) Use scrollIntoView to scroll suggestion list into view as soon as it opens.
```
suggestionList.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'nearest' });
```

## **What is the motivation/use case for changing the behavior?**
User can't see if there are any suggestions if the input field is at the edge

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all ]

*Note: Maybe this is already implemented but I can't find any documentation for the same.

**Comment by kaskar2008** [comment]
Hello @stripathix.
Thank you for this feature request :)
However we believe this is entirely a UI/UX feature. I mean this is very project specific behaviour. And about the example from bootstrap dropdown - bootstrap is a UI framework and it's meant to be "positioned smartly" :)
Feel free to change our minds 👍
