### ISSUE TITLE
Feature Request: configuration to show suggestion list only on input change

### ISSUE THREAD

**Issue by stripathix** [KazanExpress/vue-simple-suggest#127]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**
1) Click on input field
2) Start typing, some suggestions are shown.
3) Click outside of input filed triggering blur.
4) Again click on input field. Old suggestions are shown even when typing is not started.

## **What is the expected behavior?**
Some configuration to show suggestions only when the user starts typing

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Hello @stripathix. Thank you for reporting about this. Indeed this will be very handy to manage when the list is showing. We will consider this feature request in the next minor/major builds :)

Meanwhile you can do it with a Ref Method [`clearSuggestions`](https://github.com/KazanExpress/vue-simple-suggest#ref-methods) on input blur. Hope it will help you. If you have any questions left - fell free to tag me in this conversation :)
