### ISSUE TITLE
If your 'vue-simple-suggest' setup does not include a custom input component - please,

### ISSUE THREAD

**Issue by kangchals** [KazanExpress/vue-simple-suggest#128]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
The above error occurs random when the input is blured...

## **What is the expected behavior?**
The error should not occur and
the autocomplete list should hide when the input is blured.

### How are you importing Vue-simple-suggest?

- [x] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: current chrome
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]
  - latest NUXT

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Hello @kangchals.
Thank you for this bug report. Could you plaease provide us the reproduction repo/link?

P.S. If you encountered this error, please make sure that your input component emits 'focus' events properly. For more info see [Custom input documentation](https://github.com/KazanExpress/vue-simple-suggest#custom-input) (Custom input component caveats).

**Comment by kaskar2008** [comment]
Not enough information was provided.
