### ISSUE TITLE
Filter query by more than one property

### ISSUE THREAD

**Issue by gulipad** [KazanExpress/vue-simple-suggest#130]
Is there a way for the query to filter by more than one property? 

My simple-suggest iterates over a list of objects, with properties _name_, and _occupation_. My **display-attribute** is set to _name_, so it only filters by this property. I'd like the filter to work for both _name_ or _occupation_

Is it possible?

Thanks!

**Comment by kaskar2008** [comment]
Hello, @gulipad. of course you can :) You just have to use `filter` prop. it should be a function that returns Boolean value wether the item is needed or not. Function should have 2 attributes - item from the list and a query.

**Comment by gulipad** [comment]
I'll give it a shot! Thanks!!
