### ISSUE TITLE
Axios implementation

### ISSUE THREAD

**Issue by nam-co** [KazanExpress/vue-simple-suggest#131]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

Hi, thanks for the great project, I was wondering what is the best to implement axios to get results, for example <vue-simple-suggest :list="simpleSuggestionList(input)"></vue-simple-suggest>

    methods: {
      simpleSuggestionList(input) {
        axios........ input....... return results
      }
    }

**Comment by ilumos** [comment]
Here's how I've done it:

```javascript
methods: {
    searchGames(q) {
        return axios.get('games?name='+ q + '&limit=5')
            .then((response) => {
                return response.data.data;
            }, (error) => {
                console.log('Error searching games')
                console.log(error.response.status)
                console.log(error.response.data)
            })
    },
}
```

**Comment by kaskar2008** [comment]
@nam-co this feature is already exists. [API docs](https://github.com/KazanExpress/vue-simple-suggest#api-definitions). Look at the `list` prop.
