### ISSUE TITLE
Enter key on text inputs don't submit forms that use vue-simple-suggest

### ISSUE THREAD

**Issue by DragosPeta** [KazanExpress/vue-simple-suggest#134]
## **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

I'm using the vue-simple-suggest component inside a form that has a @submit.prevent event on it. If i'm pressing the enter key on a random input from the form, the form doesn't submit. I tried to set the prevent-submit prop to false, it does fix the issue but it breaks other scenarios.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Build a form that has a submit event on it
2. Add a submit button
3. Add a text input and a vue-simple-suggest component
4. Press enter inside the text input 

## **What is the expected behavior?**

The form should submit.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**

This isn't a normal behaviour because the component breaks other basic functionalities.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.13
  - Vue-simple-suggest version: 1.9.5
  - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
  - Language: ES6

**Comment by kaskar2008** [comment]
@DragosPeta Hello! Thank you for reporting about this but :) We are aware of this issue, but for now we got no free time to fix it by ourselves. But we are open to any contribution, so feel free to make this tiny library be harder, better, faster, stronger :) But we are eager to resolve this as soon as we get free of company's internal projects 👍

**Comment by Raiondesu** [comment]
@all-contributors please add @DragosPeta for Bug report
