### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rddewan** [KazanExpress/vue-simple-suggest#135]
can we display 2 column on search result like customer_id and customer_name

thank you

**Comment by kaskar2008** [comment]
Hello @rddewan!
There is a slot in our component which was created exactly for customizing the suggestion item :)

You can read some [docs](https://github.com/KazanExpress/vue-simple-suggest#custom-suggestion-item) or look at our [example](https://github.com/KazanExpress/vue-simple-suggest/blob/master/example/src/App.vue) to do so.
