### ISSUE TITLE
Show suggestions list after click in input

### ISSUE THREAD

**Issue by jakubstankowski** [KazanExpress/vue-simple-suggest#137]
hi!

It possible to show suggestions list after click in input ? 

i try this solution, but is not working:
`<div @click="testClick">
                <vue-simple-suggest
                        v-model="chosen"
                        :list="simpleSuggestionList"
                        ref="testRef"
                        :filter-by-query="true">
                    
                </vue-simple-suggest>
            </div>`
`testClick(){
                this.$refs.testRef.showList;
            },`

**Comment by kaskar2008** [comment]
Yes, it is.
You can use `min-length` prop and set it to `0`.
[More](https://github.com/KazanExpress/vue-simple-suggest#props) about `min-length`.

**Comment by jakubstankowski** [comment]
`<template>

    <div>
        <vue-simple-suggest
                v-model="chosen"
                :list="simpleSuggestionList"
                min-length="0"
                :filter-by-query="true">
            
        </vue-simple-suggest>

        <br>

        <p>Chosen element: {{ chosen }}</p>

    </div>

</template>

<script>
    import VueSimpleSuggest from 'vue-simple-suggest'
    import 'vue-simple-suggest/dist/styles.css' // Optional CSS

    export default {
        components: {
            VueSimpleSuggest
        },
        data() {
            return {
                chosen: ''
            }
        },
        methods: {
            simpleSuggestionList() {
                return [
                    'Vue.js',
                    'React.js',
                    'Angular.js'
                ]
            }
        }
    }
</script>
`

Is working **only**  when i first put something, like `vue.js`, and then after click, suggest list is display
Is still not working in first touch

You have any idea ? 
Thanks for help!

**Comment by jakubstankowski** [comment]
please re-open this issue, because is not solved

**Comment by kaskar2008** [comment]
Hello, @jakubstankowski 
As you can see from the [docs](https://github.com/KazanExpress/vue-simple-suggest#props) - `min-length` prop should be a `Number`. You are using this prop as a `String`. You have to use it with a binding: `:min-length` or `v-bind:min-length`.
