### ISSUE TITLE
Show suggest after click in input not working  [min-length=0 bugs]

### ISSUE THREAD

**Issue by jakubstankowski** [KazanExpress/vue-simple-suggest#156]
Hello!

I write this issue in this task:
- https://github.com/KazanExpress/vue-simple-suggest/issues/137

I have problem with show input suggest after click
I get response if i should change the `min-length` value to 0, but it's still not working

Somebody close the previous issue, but it not fixed

Thanks for help, is very important thinks to my

**Comment by Raiondesu** [comment]
Hello, @jakubstankowski.
We'll look into it ASAP.
In the meantime, could you please reproduce your issue using a repo or jsfiddle?

**Comment by kaskar2008** [comment]
Duplicate. Resolved in https://github.com/KazanExpress/vue-simple-suggest/issues/137
