### ISSUE TITLE
Align with browser's <datalist>

### ISSUE THREAD

**Issue by shrpne** [KazanExpress/vue-simple-suggest#166]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the expected behavior?**
Align VSS features and default options with browser's `<datalist>` implementation

- Behavior when you press Enter on VSS with opened/closed dropdown
- Allow open suggestions list with Up,Down buttons
- Tab with a hovered item should also select this item

## **What is the motivation / use case for changing the behavior?**
- Browsers implement datalist based on the W3C specification which supposed to have high-quality UX, so this  implementation can be considered as best practice
- If all implementations of autocomplete will have the same UX, then it will be easier for users to use them, because they will get used to the common behavior.

## **Please tell us about your environment:**
  
  - Vue-simple-suggest version: 1.9.5
  - Browser: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @shrpne. :)
Nice to see you again.

Thank you for this request, it makes sense for all autocompletes to have the same basic ux.

We are, however, unable to implement this ourselves due to time constraints, so a PR would be very welcome.

This would be a major-minor change, depending on which parts of API are changed.

**Comment by shrpne** [comment]
Great that you like it, I'll try to make it and split to several small PRs

**Comment by Raiondesu** [comment]
@allcontributors-bot add @shrpne for ideas

**Comment by Raiondesu** [comment]
Fixed in #175, #176 and #184.
