### ISSUE TITLE
Problem with show correct show suggest list, after connect with outside API

### ISSUE THREAD

**Issue by jakubstankowski** [KazanExpress/vue-simple-suggest#169]
Hi!
Thanks for helped my with my previous task, it's working very great.

But i have problem with connect  outside API, when i put something to suggest array, after get from API is **not visible when i put first char.**

Could you try yourself, please ? 
- clone this repository - https://github.com/jakubstankowski/simple-autosuggest-bug/blob/master/Query-Builder.vue
- then put first letter to suggest, you get something, because under the suggest i show elements from array, but **is not** visible in suggest list

The another problem is if suggest list is not show all value, i don't know why

Maybe i try connect with API in wrong solution ? Could you please add to **documentation**  right solution with outside API ? 

thanks for answer!

**Comment by kaskar2008** [comment]
Hello @jakubstankowski 
This is similar to #164 
Made some comments in https://github.com/jakubstankowski/simple-autosuggest-bug/pull/1
