### ISSUE TITLE
suggestion list does not updating on external value change

### ISSUE THREAD

**Issue by shrpne** [KazanExpress/vue-simple-suggest#185]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
External change of v-model's value doesn't affect suggestion list

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/sw09184z/2/
- focus input
- press `v` key on the keyboard
- select `Vue.js` option
- press "Clear form" button
- focus input again

Only `Vue.js` suggestion is visible for empty input now

## **What is the expected behavior?**
VSS should recalculate suggestion list and show all three suggestions when focusing empty input

### How are you importing Vue-simple-suggest?

Importing method does not affect this bug

## **What is the motivation / use case for changing the behavior?**
Developers should have a possibility to change v-model value programmatically outside of VSS, e.g. clearing form fields after form submission to prepare for new data

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.6.10
  - Vue-simple-suggest version: 1.9.6
  - Browser: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I think, to fix it we should watch `value` change, and if it is not same as inner `text` we can assume it changed externally so we should call recalculate suggestion list based on the new value

**Comment by Raiondesu** [comment]
Is there a possibility this could be fixed in #182?

**Comment by shrpne** [comment]
I don't think so, for now, on v-model's `value` change, VSS only set new `text` and nothing more

**Comment by Raiondesu** [comment]
Hmm, I guess you're right.
We gotta do something about it. Like check if the value differs and >= minLength - > update suggestions.
