### ISSUE TITLE
buggy isInFocus in Firefox

### ISSUE THREAD

**Issue by shrpne** [KazanExpress/vue-simple-suggest#187]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
VSS not set `isInFocus` to false after click on a suggestion item

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/sw09184z/3/
- focus input
- click on 'Vue.js' suggestion

Input is not focused anymore, but `isInFocus` still equals to true

## **What is the expected behavior?**
`isInFocus` should be equal to false, when input is blurred

## **What is the motivation / use case for changing the behavior?**
#186 depends on the correct `isInFocus` value

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.6.10
  - Vue-simple-suggest version: 1.9.6
  - Browser: Firefox 69
  - Language: all

**Comment by Raiondesu** [comment]
This happens because FireFox doesn't correctly process this line:
https://github.com/KazanExpress/vue-simple-suggest/blob/6e3ec969d895f48014252be369e32cfcb2085a9f/lib/vue-simple-suggest.vue#L475

I don't really remember why, though.
VSS is supposed to focus the input after suggestion click, which doesn't work in FireFox.

**Comment by Raiondesu** [comment]
Therefore, this behaviour:
> VSS not set isInFocus to false after click on a suggestion item

Is completely correct. Check in chrome. It's not set to false either. The only difference is that in Chrome input is in focus after clicking a suggestion, whereas in FF it's not.

**Comment by Raiondesu** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/19854420/66379858-f7164280-e9be-11e9-8f65-a7150c013560.png)

FireFox:
![image](https://user-images.githubusercontent.com/19854420/66379873-009faa80-e9bf-11e9-9ae3-e8db336bd76e.png)

(notice the absence of a caret in the input in FF)

**Comment by shrpne** [comment]
I will try to investigate in it

**Comment by Raiondesu** [comment]
Fixed in #188

**Comment by websquared** [comment]
Looking forward to get this fix in the next tag release.
@Raiondesu when 1.10 release is expected?

**Comment by shrpne** [comment]
I have 3999287560363908b62a48eaf50ad7e1e38dde0e in the production for some time, and looks like everything is ok with it and can be released under a tag

**Comment by Raiondesu** [comment]
Hello, @websquared, @shrpne 

There are some problems I'd like to fix before publishing the 1.10.

But now that I think of this, they could be published as a separate patch, so expect the release in a couple of hours.
