### ISSUE TITLE
Main input events take object as an argument regardless of the list structure

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#19]
## **I'm submitting a ...**
  - [X] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**

`select`, `input` and `hover` events take an object as an item argument, even if the list itself didn't contain objects.

Example:

```js
// Input list:
[ 'apple', 'banana', 'cat' ]

// `select` event's argument if 'banana' is selected
{
  title: 'banana',
  id: 1
}
```

## **What is the expected behavior?**

The prescribed events should adapt to the current list input whatever the internal converted structure is.

For example:

```js
// Input list:
[ 'apple', 'banana', 'cat' ]

// `select` event's argument if 'banana' is selected
'banana'
```

## **What is the motivation / use case for changing the behavior?**

Usability.

**Comment by kaskar2008** [comment]
Good thoughts. Agreed

**Comment by Raiondesu** [comment]
@kaskar2008, the thing is - the change in [b3b9282](https://github.com/KazanExpress/vue-simple-suggest/commit/b3b9282bb667d740c92169fe6d90da951ed54971) introduces breaking changes:
everyone using the component now recieves object instead of the plain value.

**Comment by Raiondesu** [comment]
Anyway, gonna propose a PR for minor version.
