### ISSUE TITLE
Ability to choose v-model type (object/string/index)

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#20]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**

`v-model` binds only a displayed attribute of an item (i.e. `string`)

## **What is the expected behavior?**

`v-model` binds a string (as default), a full item (object) or item's index in the list, depending on some property's value.

The property in question can be named something like `v-mode`. Or maybe something less ambiguous.

## **What is the motivation / use case for changing the behavior?**

Ability to choose the component mode depending on the circumstances. (Usability)

**Comment by Raiondesu** [comment]
Implemented in [v-model-mode](https://github.com/KazanExpress/vue-simple-suggest/tree/v-model-mode) branch.
Not working well.
Help needed.

**Comment by kaskar2008** [comment]
@Raiondesu, Got it
