### ISSUE TITLE
Release 1.10.0 includes .git subfolder

### ISSUE THREAD

**Issue by sullivanpt** [KazanExpress/vue-simple-suggest#207]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

Release 1.10.0 on npm includes the ".git" subfolder. This causes problems with subsequent npm commands such as the excerpt below.  In addition, it looks like the normal release process wasn't used as 1.10.0 is not listed in the GitHub releases.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Install vue-simple-suggest, then try to install another npm module. Example:

```
$ npm install vue-simple-suggest
$ npm install @vue/test-utils
npm ERR! git C:\myproject\node_modules\vue-simple-suggest: Appears to be a git repo or submodule.
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

## **What is the expected behavior?**

npm releases should not include a folder named ".git"

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

N/A

## **What is the motivation / use case for changing the behavior?**

N/A

## **Please tell us about your environment:**
  
 - Windows 10
 - npm Version: 6.11.3
  - Vue.js Version: N/A
  - Vue-simple-suggest version: 1.10.0
  - Browser: N/A
  - Language: N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @sullivanpt.
Wow, that's clearly unintentional. We'll fix this soon!

**Comment by josselinlbe** [comment]
Same problem! Our pipeline with herokuish image:

```
remote: -----> Pruning devDependencies        
remote:        npm ERR! code EISGIT        
remote:        npm ERR! path /tmp/build/node_modules/vue-simple-suggest        
remote:        npm ERR! git /tmp/build/node_modules/vue-simple-suggest: Appears to be a git repo or submodule.        
remote:        npm ERR! git     /tmp/build/node_modules/vue-simple-suggest        
remote:        npm ERR! git Refusing to remove it. Update manually,        
remote:        npm ERR! git or move it out of the way first.        
remote:                
remote:        npm ERR! A complete log of this run can be found in:        
remote:        npm ERR!     /tmp/npmcache.Dt6Vp/_logs/2019-11-02T12_56_48_665Z-debug.log        
remote:                
remote: -----> Build failed        
remote:                
remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
remote:                
remote:        Some possible problems:        
remote:                
remote:        - Node version not specified in package.json        
remote:        https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version        
remote:                
remote:        Love,        
remote:        Heroku          
```

**Comment by kaskar2008** [comment]
This is a known bug in npm@6.9.1 and it has been fixed. I'm on the fix from our side tho :)

**Comment by kaskar2008** [comment]
Patched!

**Comment by kaskar2008** [comment]
Release list has been updated accordingly. [1.10](https://github.com/KazanExpress/vue-simple-suggest/releases/tag/v1.10.1) has been added
