### ISSUE TITLE
onRequestDone list pass into autocompleteText

### ISSUE THREAD

**Issue by DoubleTime** [KazanExpress/vue-simple-suggest#213]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
If my result is one, I want it to auto select the first result and close the suggestion list. Like Ctrl+Enter behavior. 
```
 onRequestDone (list) {
    if(list.length == 1){
        //My suggestion input is dynamic
        this.$refs.suggestInput[this.rows_input.length-1].autocompleteText(list[0]);
    }
}
```
In this case the simple-suggest input will just return `[object Object]`.
`autocompleteText` require argument suggestion, how do I convert the list to suggestion ?

Thanks
### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [x] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Hello @DoubleTime 
You can use `suggestions` from [Ref Data](https://github.com/KazanExpress/vue-simple-suggest#ref-data).

Also you could use a `select` method from [Ref Methods](https://github.com/KazanExpress/vue-simple-suggest#ref-methods).

**Comment by Raiondesu** [comment]
Another solution would be to use `@request-done` from [Emitted Events](https://github.com/KazanExpress/vue-simple-suggest#emitted-events).
