### ISSUE TITLE
Showing no results randomly

### ISSUE THREAD

**Issue by Jagdeep-Sharma** [KazanExpress/vue-simple-suggest#232]
## **I'm submitting a ...**
  - [ ] bug report

## **What is the current behavior?**
When user starts typing sometimes it shows no results despite 'request-done' event has data to show. This occurs randomly.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
[https://ibb.co/nkms5gB](url)

### How are you importing Vue-simple-suggest?
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
</script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Hello!
Could you please provide the steps to reproduce and if possible a minimal demo of the problem. The link you have left is invalid.

**Comment by kaskar2008** [comment]
Not enough information.
