### ISSUE TITLE
min-length and debounce

### ISSUE THREAD

**Issue by mymails838** [KazanExpress/vue-simple-suggest#235]
Hello,
not sure if this is the right place to ask question or not, if not please direct me to the proper place. I use this component and it seems to be working but I want to change the min-length to 0 but no matter what I do, I always got a vue warning message of 

Invalid prop: type check failed for prop "minLength". Expected Number with value 0, got String with value "0".

This is what I did

<vue-simple-suggest min-length="0" placeholder="Search Address" v-model="searchData" display-attribute="address" value-attribute="linkid" :list="getAddressList" v-on:select="selectAddress"></vue-simple-suggest>

Thank you very much for any help.

Howard

**Comment by kaskar2008** [comment]
Hello!
You probably should look through the [vue props binding documentation](https://vuejs.org/v2/guide/components-props.html) ([Passing numbers](https://vuejs.org/v2/guide/components-props.html#Passing-a-Number) to be more precise)

Long story short: any props passed to the component w/o binding are strings. if you want to pass a prop as a number - make it through `v-bind`.

**Comment by mymails838** [comment]
Hello,
Thank you very much for the info. I did try v-bind:debounce="0" and the warning message goes away but it does not work as expected. When I just do debounce="0", the drop down work right away with just one character but when I do v-bind:debounce="0", it will not work until I enter at least 2 characters. I even specify v-bind:min-length="0" but get the same result, have to enter at least 2 characters for the drop down to appear

Thanks,
Howard

**Comment by kaskar2008** [comment]
Ok, we'll try to investigate this today if you can provide us a minimal reproduction repo/demo

**Comment by mymails838** [comment]
Thank you very much for all your help. I created 2 fields, one with v-bind on debounce and the other without using v-bind. Here are my codes

<div>
<p>Using v-bind for debounce</p>
<vue-simple-suggest :debounce="0" v-model="chosen" display-attribute="full_name" value-attribute="id" :list="getGitHubList"></vue-simple-suggest>
<p>without v-bind for debounce</p>
<vue-simple-suggest debounce="0" v-model="chosen1" display-attribute="full_name" value-attribute="id" :list="getGitHubList1"></vue-simple-suggest>
</div>

<script>
data: function(){
   return { chosen: "", chosen1: "" };
},
methods: {
getGitHubList() {
            return fetch('https://api.github.com/search/repositories?q=' + this.chosen, { method: 'GET' })
            .then(response => response.json())
            .then(json => json.items);
        },
getGitHubList1() {
            return fetch('https://api.github.com/search/repositories?q=' + this.chosen2, { method: 'GET' })
            .then(response => response.json())
            .then(json => json.items);
        }
}
</script>

**Comment by mymails838** [comment]
Sorry but seem like my codes did not show up properly so I attach the file instead.

Thank you,

[test.txt](https://github.com/KazanExpress/vue-simple-suggest/files/3922668/test.txt)

**Comment by kaskar2008** [comment]
Hello @mymails838 
Sorry for this delay. You misunderstood the purpose of the `list` attribute. If you want it to be a function in which you will do something with the entered text - it could get current entered text as a single argument. So querying `this.chosen` is an incorrect solution. You should do it like this:

```js
methods: {
	getGitHubList(query) {
        return fetch('https://api.github.com/search/repositories?q=' + query, { method: 'GET' })
        .then(response => response.json())
        .then(json => json.items);
    }
}
```

**Comment by mymails838** [comment]
thank you very much for all your help. it works perfectly now.
