### ISSUE TITLE
suggestionClick not working

### ISSUE THREAD

**Issue by poornimasudha** [KazanExpress/vue-simple-suggest#244]
## **I'm submitting a support request.**
  
I need to  show  an alert box when an item is selected  from the dropdown.Now it is not showing*

```vue
<template>
    <div>
        <vue-simple-suggest @suggestionClick="sug"
                v-model="chosen"
                :list="simpleSuggestionList"
                :filter-by-query="true">
        </vue-simple-suggest>
        <br>

        <p>Chosen element: {{ chosen }}</p>
    </div>
</template>

<script>
    import VueSimpleSuggest from 'vue-simple-suggest';
    import 'vue-simple-suggest/dist/styles.css' // Optional CSS
    export default {
        name: "suggest",
        components: {
            VueSimpleSuggest
        },
        data() {
            return {
                chosen: ''
            }
        },
        methods: {
            sug(){
               alert("jiji");
            },
            simpleSuggestionList() {
                return [
                    'Vue.js',
                    'React.js',
                    'Angular.js'
                ]
            }
        }
    }
</script>

<style scoped>

</style>
```

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [x] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
@poornimasudha You are using `suggestionClick` event, which is incorrect. It should be `suggestion-click`. You can find more information about events [here](https://github.com/KazanExpress/vue-simple-suggest#emitted-events)

**Comment by poornimasudha** [comment]
<template>
    <div>
        <vue-simple-suggest @suggestion-click="symptoms()"
                v-model="chosen"
                :list="simpleSuggestionList"
                :filter-by-query="true">
        </vue-simple-suggest>
        <br>

        <p>Chosen element: {{items }}</p>
    </div>
</template>

<script>
    import VueSimpleSuggest from 'vue-simple-suggest';
    import 'vue-simple-suggest/dist/styles.css' // Optional CSS
    export default {
        name: "suggest",
        components: {
            VueSimpleSuggest
        },
        data() {
            return {
                chosen: '',
                items:[]
            }
        },
        methods: {
            symptoms(suggestion){
                this.items.push(suggestion)
                console.log(suggestion)
            },
            simpleSuggestionList() {
                return [
                    'Vue.js',
                    'React.js',
                    'Angular.js'
                ]
            }
        }
    }
</script>

<style scoped>

</style>

still I am not getting the selected element on suggestion variable.

**Comment by kaskar2008** [comment]
@poornimasudha 
This is expected behaviour, because you are binding the method using inline JavaScript statement. Just bind the method itself to the event and you will get desirable effect. See more information about method bindings at the [Vue.js documentation](https://v1.vuejs.org/guide/events.html)
