### ISSUE TITLE
value-attribute not returning variable but complete object

### ISSUE THREAD

**Issue by amchconsult** [KazanExpress/vue-simple-suggest#245]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
When using mode="select" is returning an the object and not the assigned value-attribute="_id"
why?

```
var datacharts = [{"_id":19,"code":"10100","name":"Checking","status":"ACTIVE","type":"Bank"},{"_id":115,"code":"10300","name":"Savings","status":"ACTIVE","type":"Bank"}]


<vue-simple-suggest
    v-model="code_id"
    value-attribute="_id"
    display-attribute="name"
    :list="datacharts"
    mode="select"
    :max-suggestions="0"
    :filter-by-query="true"
    :destyled=false
></vue-simple-suggest>
```

before:

```json
[
    {
        "_id":1,
        "auditlog":null,
        "code_id":19,
        "datecreated":"2019/12/09",
        "notes":null,
        "recognized":"Manual",
        "reconciled":"N",
        "taxline":"N",
        "trans_amount":"1234.50",
        "trans_date":"2019-12-09",
        "trans_description":"Expense test",
        "trans_num":null,
        "trans_payee":null
    }
]
```

After selecting, I get this:

```json
[
    {
        "_id":1,
        "auditlog":null,
        "code_id":{"_id":115,"code":"10300","name":"Savings","status":"ACTIVE","type":"Bank"},
        // I should get "code_id": 115,
        "datecreated":"2019/12/09",
        "notes":null,
        "recognized":"Manual",
        "reconciled":"N",
        "taxline":"N",
        "trans_amount":"1234.50",
        "trans_date":"2019-12-09",
        "trans_description":"Expense test",
        "trans_num":null,
        "trans_payee":null
    }
]
```

## **What is the expected behavior?**
return the assigned value-attribute="_id" not the complete object.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [x] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
@amchconsult you are using select mode (`mode="select"`). This is expected behaviour. See more info in [documentation](https://github.com/KazanExpress/vue-simple-suggest#mode)
