### ISSUE TITLE
When empty list is returned by query, then "no results" is not handled properly.

### ISSUE THREAD

**Issue by lauri911** [KazanExpress/vue-simple-suggest#25]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
When empty list is returned by query, then "not found" is not handled properly.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1) open https://kazanexpress.github.io/vue-simple-suggest/
2) type "adfasdfasdf"
3) you will see a line appearing below input (empty dropdown is show).

## **What is the expected behavior?**

One way to handle it:

Create a special slot "no-results" - then user can handle it (pass "query" to this slot as well)

At moment you have this layout:
1) miscItemAbove
2)     suggestItems
3) miscItemBelow

...and question is how to hande "no-results" layout. 
I prefer this, because header and footer are usually about results, no-result is handled differently:
With results:
  1) miscItemAbove
  2)     suggestItems
  3) miscItemBelow
Without results:
  1) no-results slot

If "no-results" slot is not defined by user, then hide dropdown completly.
For example, for hidding dropdown use 
computed:
   hasNoResultsSlot () {
      return !!this.$scopedSlots['no-results'];
    } 

PS. Please use same convention for slot names - camelCase or kebab-case, not mixed.
Its hard to remember, was it miscItem-above or miscItem-Above or miscItem-Above or misc-ItemAbove. (Maybe rename them: results-header and results-footer)

**Comment by lauri911** [comment]
On second tought, user can handle "no results" in miscItem-above as well.

**Comment by kaskar2008** [comment]
@lauri911 We are glad that you are interested in our little project.

As a possible workaround we can provide a prop `show-empty` that will triggers whether the empty list will be shown or not.

And yes, the `No-result` can be fulfilled with `misc-item-above/misc-item-below` slots. I will update the example for this showcase.

About slot names - you are right, we have overlooked this terrible mistake. Will be fixed in the next patch.

**Comment by Raiondesu** [comment]
@kaskar2008, hiding an empty list is not a problem, actually. This can be published as a separate patch.

Slot names, however, should be out as a separate minor release, unfortunately.

**Comment by Raiondesu** [comment]
@lauri911, here's how what you described can be achieved now:
```html
<!-- Main slot template -->
<template slot="miscItem-above" slot-scope="{ suggestions, query }">
  <!-- Sub-template if have any suggestions -->
  <template v-if="suggestions.length > 0">
    <div class="misc-item">
      <span>You're searching for '{{ query }}'.</span>
    </div>
    <div class="misc-item">
      <span>{{ suggestions.length }} suggestions are shown...</span>
    </div>
    <hr>
  </template>
  <!-- Show "No result" otherwise -->
  <template v-else>
    <div class="misc-item">
      <span>No results</span>
    </div>
  </template>
</template>
```

We will update the documentation to include this use-case.

**Comment by Raiondesu** [comment]
Also, it turns out that a `scopedSlot` is always a function that always returns an array with at least one element.

So this:
```js
hasNoResultsSlot () {
  return !!this.$scopedSlots['no-results'];
}
```
will not work.

**Comment by lauri911** [comment]
Hmm, it works for me very well:
https://jsfiddle.net/eywraw8t/4361/

**Comment by Raiondesu** [comment]
@lauri911, forgot to mention that it was the case for functional components, which `vue-simple-suggestion` can become using `vue-template-compiler`.

**Comment by Raiondesu** [comment]
My bad. Turns out that the slot function behaves differently on a rendering tick. We're close to solution now.

**Comment by Raiondesu** [comment]
Thanks for pointing out so many issues, @lauri911.
👍
