### ISSUE TITLE
SCRIPT1002: Syntax error message in IE11

### ISSUE THREAD

**Issue by jnegley-bha** [KazanExpress/vue-simple-suggest#260]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
IE11 throws an 

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [x] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jnegley-bha** [comment]
Sorry... submitted request accidentally before completing the details...

Working with cursed IE11 and upon importing into app.vue I get the "SCRIPT1002: Syntax error". I have imported the polyfills.

Don't know how to begin to troubleshoot this problem. Any insights would be helpful.

**Comment by jnegley-bha** [comment]
Further detail... the syntax error occurs in the **./node_modules/vue-simple-suggest/dist/es6.js** file.

**Comment by kaskar2008** [comment]
Hello @jnegley-bha
Can you provide us a minimal reproduction link (repo/fiddle/any sandbox)?

**Comment by brickgale** [comment]
any solutions on this? i'm also currently encountering this problem.

**Comment by brickgale** [comment]
found a solution, using `vue-simple-suggest/dist/cjs'` resolves this error.
