### ISSUE TITLE
add placeholder prop

### ISSUE THREAD

**Issue by yinzhida** [KazanExpress/vue-simple-suggest#285]
## **I'm submitting a ...**
  - [ ] bug report
  - [*] feature request
  - [ ] support request

## **What is the current behavior?**
has not placeholder prop

## **What is the expected behavior?**

add placeholder prop

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [*] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @yinzhida.

Currently, all props, that are not stated explicitly in documentation, are forwarded onto the `<input>` component inside vue-simple-suggest.

Therefore, you can just pass the `placehoder` prop as you'd do on any `<input>`.

[Reference here](https://github.com/KazanExpress/vue-simple-suggest#custom-input).

I'm closing this issue, as the feature is already implemented.
