### ISSUE TITLE
Rename `list` prop into `source`

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#29]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the motivation / use case for changing the behavior?**

It would be more convenient, since `source` is lexically more general than `list`.

Potential milestone for next version.

**Comment by lauri911** [comment]
Source --- it can be URL for example. You can think that way: source is place from where you get water. But here you are passing water. 

You are passing "Collection of items to be listed", so items, list-items, items-collection ....

**Comment by lauri911** [comment]
Too general. 
This list property needs refactoring. You are doing two-in-one now.
I suggest to do two separate properties:
1) initial-list -> array
2) updateList(query) -> function for update items
Then one can send initial list and update list when query changes.

In this case one does not need to look documentation/implementation every time to understand, what this property does.

**Comment by kaskar2008** [comment]
@lauri911 you've got the point, but that was the idea to implement a prop that handles a list, no matter how exactly user wants to declare his list, in the first place.

**Comment by lauri911** [comment]
In this case maybe "item-source" or "list-source" will be better.
I understand that as well, that it is cool to have throw whatever to component, but explicit code is easier to understand without documentation. Especially after 6 months from now :)
But there is no good or bad way, just discussing :)

**Comment by Raiondesu** [comment]
The main goal of a single prop for list source is not "being implicit" about the data source. Its main goal is to give the programmer freedom to choose whether the list source is explicit or not.

It might appear as implicit by-default, but it's not. Mainly because such an approach (single prop) forces the programmer to explicitly define the way to handle lists' defaults and updates without any boilerplate code or other garbage.

So adding another prop for default lists or URLs will restrict and diminish the functionality of the component, not extend it.


But, after all, a different name for the prop in question is really mandatory.

**Comment by lauri911** [comment]
Agree.
In this case maybe you should accept  `array`, `function` and `string`  in `source` prop.

And string is expected to be URL in form `https://url.com/?whatever&youroption={query}` and you replace `{query}` and you will fetch data in component.

**Comment by kaskar2008** [comment]
@lauri911 About url and a query - I think this is a bad idea to force people using nothing but REST architectural style. Keeping the implementation "outside-the-box" is also allowing us to give user variety of tools to work with (fetch or XMLHttpRequest - for example).

**Comment by Raiondesu** [comment]
Sorry, but no. We'd be glad to add this in the first place, but there's a problem.

Accepting a URL into the component also forces us to implement a specific REST logic under-the-hood. This means that the component would force users to have REST-dependent code in the final application even if they don't use REST (GraphQL, SOAP, etc. - for example). This definitely would piss off many people as well as greatly increase the amount of rarely used code in the component.

Right now, even without any customizations or configs when using the component - 100% of the code is executed, because the code is 100% useful for everyone using the component. This would no longer be the case if we were to implement implicit URL & REST support. Mainly because this (as I said) requires REST-specific logic to be implemented, while also tying it to a specific implementation of REST (`XmlHttpRequest`, `fetch` or whatever) and data format (JSON, XML or whatever) with no regards to how the end-user would like to implement such a thing.

And there're plenty of examples when such a simple and useful (on the first thought) logic becomes toxic for the developers. The most recent one I stumbled upon - issue charliekassel/vuejs-autocomplete#24.

So, we really want to keep things clean, as they are.

And, after all, didn't you talk about how important it is to be explicit about API's one message before, @lauri911? :)

**Comment by lauri911** [comment]
:)
Exactly, that was my point, when there is something with "general" name, you don't know just by reading it, what it does accept.
So getData, fetchData etc. -- its very clear without looking, function here.
Items, listItems, itemCollection, list etc. -- almost clear that we are talking about data collection here.

About functionality, of course, accepting list or function is fine, because sometimes this list is filled by backend in template and one does not need implement getData function.
But how to name it?  
Thats why I personally like to different props here --- and I even can fill them both, in this case given data is initial and after some typing it will be overwritten by results from function. But looking at component I know right away, which one I am passing and prop name will tell me what to pass.

**Comment by Raiondesu** [comment]
Well, in case of setting the default value - the component already has one: `value` prop.
Then what's the point of adding another default-value-prop?

**Comment by kaskar2008** [comment]
It's been a week and I had some time to think about it. Now I see that a prop name `list` is much better. Maybe we don't need to rename it at all?

**Comment by Raiondesu** [comment]
@kaskar2008, why do you think so?
Can you please provide any arguments on your opinion?

**Comment by Raiondesu** [comment]
Well... It's still an arguable topic though. Any contribution to this discussion would be valuable AF.

**Comment by kaskar2008** [comment]
I'm closing this issue duo to lack of arguments.
