### ISSUE TITLE
Conditional css to individual suggestion/disabled suggestion

### ISSUE THREAD

**Issue by dhruvaaronwalter** [KazanExpress/vue-simple-suggest#299]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - or [x] support request

## **What is the current behavior?**
The suggest-item class drives the styling for all the suggestion items. Is there any way to apply different css to some of the suggestions based on a condition (like v-bind:css)? Any help would be appreciated, cheers!

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**

I am using the control as a drop-down with suggestions, and i need to show some of the suggestions grayed-out to show inactive status.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.6.11
  - Vue-simple-suggest version: 1.10.1
  - Browser: Chrome,

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by xlcrr** [comment]
We were just about to raise the same issue.

We have a list of fonts, and we would like to apply the font-family to each item in the list

Is this possible with the current framework?

**Comment by ciaranpflanagan** [comment]
This is more of a work around then solving the issue, but we found you can use custom suggestion items.(https://github.com/KazanExpress/vue-simple-suggest#custom-suggestion-item)

Something like `<div><span :style="suggestion.style">{{ suggestion.text }}</span></div>` which would apply the styles to the individual dropdown items.

**Comment by dhruvaaronwalter** [comment]
> This is more of a work around then solving the issue, but we found you can use custom suggestion items.(https://github.com/KazanExpress/vue-simple-suggest#custom-suggestion-item)
> 
> Something like `<div><span :style="suggestion.style">{{ suggestion.text }}</span></div>` which would apply the styles to the individual dropdown items.

@ciaranpflanagan This is awesome mate, works for me! Thanks so much

**Comment by dhruvaaronwalter** [comment]
> We were just about to raise the same issue.
> 
> We have a list of fonts, and we would like to apply the font-family to each item in the list
> 
> Is this possible with the current framework?

I used the link provided by @ciaranpflanagan to use the 'suggestion-item' slot like this:
```
<vue-simple-suggest>
    <div slot="suggestion-item" slot-scope="{ suggestion }">
          <span v-bind:class="bindSuggestionCss(suggestion, 1)">{{ suggestion.value }}</span>
    </div>
</vue-simple-suggest>
```

So i can use a custom function to bind a css to a suggestion based on the suggestion item. The suggestion item will include all the attributes based on your input list.
I think something like this should work for you. Let me know if it helps.
