### ISSUE TITLE
Auto-install, if included via script tag

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#32]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**

The component needs to be defined explicitly, when included via `<script>`. This makes clean umd build impossible to use in the browser.

## **What is the expected behavior?**

The component would register itself in the Vue instance, if it's presented in global scope.

**Comment by kaskar2008** [comment]
Cool!
