### ISSUE TITLE
List is not shown immideately if min-length is 0

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#34]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

Currently, if `min-length` is `0` - the list won't show on click/focus.

## **What is the expected behavior?**

I expect it to show on whatever `min-length` is set.

**Comment by Raiondesu** [comment]
Reopening this due to reworks in slot-detection mechanisms.

**Comment by hannesaasamets** [comment]
Existence of min-length prop is not docummented in the readme.

**Comment by kaskar2008** [comment]
@hannesaasamets Thank you for pointing that out. We will add it ASAP.

**Comment by kaskar2008** [comment]
@hannesaasamets docs are updated [vue-simple-suggest Props](https://github.com/KazanExpress/vue-simple-suggest#props)
