### ISSUE TITLE
[vue-router] Failed to resolve async component default: Syntax Error. IE11 error.

### ISSUE THREAD

**Issue by wahiche-ideal** [KazanExpress/vue-simple-suggest#354]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
On IE 11, it does not load the component.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Go to IE 11, it won't show up.

## **What is the expected behavior?**
It works in IE11

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.21
  - Vue-simple-suggest version: 1.10.1
  - Browser: [IE 11]
  - Language: [ES6]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

[vue-router] Failed to resolve async component default: Syntax Error
[vue-router] uncaught error during route navigation:
[object Error] {description: "Syntax error", message: "Syntax error", name: "SyntaxError", number: -2146827286, stack: "SyntaxError..."}

**Comment by kaskar2008** [comment]
Hello @wahiche-ideal 

Try to import as described in these section of docs: [Imporing](https://github.com/KazanExpress/vue-simple-suggest#importing) and [Polyfills](https://github.com/KazanExpress/vue-simple-suggest#polyfills)

**Comment by wahiche-ideal** [comment]
So I would say that it is a bit misleading and I don't understand the decision to have specific polyfills for each type of import, also to have a polyfil import that does not cover all the polyfils.

None the less I was able to make it work using the CommonJS import without the polyfill.

I appreciate the hard work, and the quick response.
