### ISSUE TITLE
Is there a way to accept values that are not from the list?

### ISSUE THREAD

**Issue by rajkishan16** [KazanExpress/vue-simple-suggest#376]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
When a query is entered in the text box, if any values match that query, it lists those values, and if not, nothing is shown.

## **What is the expected behavior?**
Is there a way to accept values that are not from the source data? Maybe some kind of event when the user presses Enter where I can get the new value?

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [x] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
It would make it easier to accept new values, and select existing ones.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.6.11
  - Vue-simple-suggest version: 1.10.3
  - Browser: all
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
This seems to be an awesome control. Thanks for developing this.

**Comment by DPvic** [comment]
You can easilly acomplish this with a form

```
<form @submit.prevent="onSubmitWhatever">
          <vue-simple-suggest
              v-model="chosen"
              :list="simpleSuggestionList"
          >
          </vue-simple-suggest>
</form>
```

**Comment by rajkishan16** [comment]
I think that should work for me. Thanks a lot!
