### ISSUE TITLE
Execute search on ArrowDown if no suggestions provided?

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#38]
## **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**

Currently, if there's no suggestions (suggestion list is empty), the list will be shown only after pressing Enter (executing `list/getSuggestions` function). The intuitive `arrow down` (show-list-key) will do nothing in this context.

## **What is the expected behavior?**

When there're no suggestions, the pressing of `arrow down` (show-list-key) would also work the same way as pressing the `Enter` (search-key), but only in this specific context. In all other contexts, the `arrow down` (show-list-key) would only show the list of suggestions.

Such a behaviour currently would only be achieved only by including the `arrow down` (show-list-key) in same control section where  the `Enter` (search-key) is now. Which is not convenient at all.

## **What is the motivation / use case for changing the behavior?**

In the case of showing the suggestions when there's none, it seems convenient to me to search for them.

**Comment by kaskar2008** [comment]
Yeah, looks pretty decent. We definitely need this!

**Comment by Raiondesu** [comment]
I'm on it then.

**Comment by jabui** [comment]
This seems to be broken now?

**Comment by Raiondesu** [comment]
@jabui, seems to be related to #34

**Comment by jabui** [comment]
👍 BTW min-length prop is not documented

**Comment by kaskar2008** [comment]
@jabui Thank you for pointing that out :) We will add it ASAP.

**Comment by kaskar2008** [comment]
@jabui docs have been updated [vue-simple-suggest Props](https://github.com/KazanExpress/vue-simple-suggest#props)
