### ISSUE TITLE
operate as a standard `select` 

### ISSUE THREAD

**Issue by mikeerickson** [KazanExpress/vue-simple-suggest#385]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [x] support request

## **What is the current behavior?**

I am trying to figure out a way to configure to work as a standard `<select>` control, whereby clicking on the object would display the menu with all choices, regardless of what is in the `v-model`  

Is this possible, I cant find anything in the docs which would give me what I am looking for.

Control by default

![image](https://user-images.githubusercontent.com/183153/101707128-6e21ed80-3a3f-11eb-9e56-64c2c79b65c6.png)

Control on mouseover:

![image](https://user-images.githubusercontent.com/183153/101707314-d96bbf80-3a3f-11eb-9a0f-31fe9f499c38.png)

Control when clicking in edit field with no value (this is what I want to have display at all times, regardless of what is in input value, giving the user ability to select from list as a normal `<select>`)

![image](https://user-images.githubusercontent.com/183153/101707180-914c9d00-3a3f-11eb-9533-bd43bb70ab4a.png)

### How are you importing Vue-simple-suggest?

- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)

## **What is the motivation / use case for changing the behavior?**

I am trying to get a consistent control (appearance wise) for both suggest menus (with current typeahead functionality) and standard select controls.  I have it configured visually exactly as I want it, but need to have both controls.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.6.12
  - Vue-simple-suggest version: 1.10.1

**Comment by kaskar2008** [comment]
Hello @mikeerickson 
Sorry for the long reply. You can use `min-length` prop and a static list rather than a function, set `min-length` to 0 and it will behave as a dropdown
