### ISSUE TITLE
TypeError: this.inputElement is null

### ISSUE THREAD

**Issue by tbl0605** [KazanExpress/vue-simple-suggest#417]
Hi,
I'm getting a `"TypeError: this.inputElement is null"` error when using vue-simple-suggest on custom inputs and using Webpack's lazy loading globally (in "eager" mode) with prefetch disabled.
The bug occurs only the first time a view component is used (because of lazy loading), further instances seem to work correctly.

The problem is (somehow) also described here: https://forum.vuejs.org/t/not-getting-refs-in-mounted/12490
The root cause is that `$refs` is not always available in the `mounted` lifecycle hook.

I've created a projet to easily reproduce this issue (see the README.md file of the project for more details) :
https://github.com/tbl0605/vue-bug-simple-suggest

So basically this bug appears (for me) when:
- using "eager" mode on vue-router routes
```
component: () => import(/* webpackMode: "eager" */ './views/MyView.vue')
```
- disabling prefetch in `vue.config.js`
```
config.plugins.delete('prefetch');
```
- using dynamic component loading
```
const componentContext = require.context(
  '@/components',
  true,
  /\w\d*\.vue$/i,
  'eager'
);
componentContext.keys().forEach(componentFilePath => {
  const componentName = upperFirst(
    camelCase(
      componentFilePath
        .split('/')
        .pop()
        .replace(/\.vue$/, '')
    )
  );
  const componentContent = componentContext(componentFilePath);
  const componentConfig = componentContent.default || componentContent;
  if (componentConfig instanceof Promise) {
    Vue.component(componentName, () => componentConfig);
  } else {
    Vue.component(componentName, componentConfig);
  }
});
```

## Workaround:
I've patched the `mounted` method in `vue-simple-suggest.vue` to delay initialization to be done after the first component rendering:
```
  mounted () {
    setTimeout(() => {
      this.inputElement = this.$refs['inputSlot'].querySelector('input')
      this.setInputAriaAttributes()
      this.prepareEventHandlers(true)
    }, 0)
  }
```

Maybe it can be done otherwise, but in my case, it works well ;)

**Comment by kaskar2008** [comment]
Hello, @tbl0605!

Thank you for this bug report. Sorry for the long reply.
