### ISSUE TITLE
destyled prop is not working in source importing

### ISSUE THREAD

**Issue by kaskar2008** [KazanExpress/vue-simple-suggest#43]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

`:destyled="true"` not working properly when you importing the source: it only affects the `input` element

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```js

import VueSuggest from 'vue-simple-suggest/lib'

```

```html

<vue-suggest :destyled="true" />

```

## **What is the expected behavior?**

Suggestion items should be destyled as well.

**Comment by Raiondesu** [comment]
Fixed in #45
