### ISSUE TITLE
hide scrollbar

### ISSUE THREAD

**Issue by josephshepin** [KazanExpress/vue-simple-suggest#472]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [x] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**

the scrollbar can be ugly or not needed.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Scrollbar styling is definitely not this component's responsibility. You can style visual part as pretty as you want  without adding new features to this component :)
