### ISSUE TITLE
Maybe do not hide the list, if minLength === 0?

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#48]
## **I'm submitting a ...**
  - [X] bug report?
  - [X] feature request
  - [ ] support request

## **What is the current behavior?**

Currently, if the text length gets to 0, with `min-length` prop also being 0, the suggestion list will hide, even if it contains something (a default list, for example).
It will become visible again after clicking on input, though.

## **What is the expected behavior?**

I expect some way to keep the list showed even with the absence of text.

## **What is the motivation / use case for changing the behavior?**

It seems much more convenient to me to still show the list, if the minlength is 0 and there are some suggestions around.

**Comment by kaskar2008** [comment]
Yes, you are right. The list must be shown if `min-lenght` equals 0 and suggestion list is not empty.
