### ISSUE TITLE
Specify custom input component caveats in the docs

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/vue-simple-suggest#51]
Currently, there's absolutely no clue on what exact API must custom input component expose to work with vue-simple-suggest.

It needs to be specified, I think, that custom input component **must**:
- Emit an `input` event
- Emit `focus` and `blur` events
- Have a `value` prop
- ??? (What else?)

**Comment by hannesaasamets** [comment]
Is this a complete list of requirements? Could there be an example be in the docs?

**Comment by Raiondesu** [comment]
Hmm... Now thinking about it and it seems like the custom input component doesn't have to have `input` event and `value` prop. `focus` and `blur` are vital, however.
Seems like nothing else should be present.

P.S. This issue was created due to not having a finalized approach for custom input components handling at the time. I'll mark it as obsolete now and add a remark on the topic to the docs.

**Comment by hannesaasamets** [comment]
I'm having trouble using a custom input. Is there something about the v-model of the custom input & the vue-simple-suggest I should pay attention to? Do I have to update them manually?

**Comment by Raiondesu** [comment]
Seems like this one is not completely closed due to #61.
There must be some other caveats that aren't specified yet.
