### ISSUE TITLE
Provide a more intuitive way of keeping the list shown after suggestion click

### ISSUE THREAD

**Issue by skamv** [KazanExpress/vue-simple-suggest#52]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the current behavior?**
After clicking on a suggestion item the suggestions list becomes hidden ([here](https://github.com/KazanExpress/vue-simple-suggest/blob/6d41667a38731209de507d2813a4c23b969b150a/lib/vue-simple-suggest.vue#L288))

## **What is the motivation / use case for changing the behavior?**
After clicking on a suggestion item I want the suggestions list to optionally keep showing.

**Comment by kaskar2008** [comment]
We can provide an optional tool to create a custom pipe after the click, so we can check whether to run default callbacks or not. But I can't imagine the interface itself.

**Comment by skamv** [comment]
@Raiondesu Thanks for your response. 

Your suggestion to use vue event handling to stop the event propagation solves my problem. It does not feel too hacky for my use-case.

My first thought was to introduce a new boolean Prop. Something like `keep-showing-suggestion` and then conditionally hide/keep the suggestion list when handling `suggestionClick`.

**Comment by Raiondesu** [comment]
@skamv, I think one way of handling this would be to introduce a prop for an override for the default click, instead of a boolean. But it would be just a simple "syntax sugar" for this exact use-case.

**Comment by Raiondesu** [comment]
I'm glad that my answer solved the issue, though.
