### ISSUE TITLE
Improve "bolden" example - single character "b"

### ISSUE THREAD

**Issue by willplaehn** [KazanExpress/vue-simple-suggest#53]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
When the single letter "b" is entered and a suggestion list is populated, Multiple \<b\> tags are created. This appears to be because of the multiple-passes approach used to handle different capitalizations. See screenshot.

![image](https://user-images.githubusercontent.com/10226784/39148221-ba069a24-4709-11e8-95b4-eec90702213d.png)

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. https://kazanexpress.github.io/vue-simple-suggest/
2. Type b plus two additional letters to get suggestions list to appear (e.g. "bab")
3. Delete characters until only "b" is in the input box

## **What is the expected behavior?**

Correct highlighting!

## **What is the motivation / use case for changing the behavior?**

For use cases where suggestions are given for a single character, this is a serious issue vs. just an edge case as in the scenario above.

## **Please tell us about your environment:**
  
N/A

## **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Suggesting to do it in one pass to avoid this issue. We can also make the function more understandable and avoid enumerating each capitalization case by using a case-insensitive regex.

Here is an example function that mitigates the issue. `texts` is also modified from the original to split on commas. Submitting this as an issue vs. a PR because I'm not sure if it covers all of your edge cases.

```javascript
boldenSuggestion({ suggestion, query }) {
  let result = this.$refs.suggestComponent.displayProperty(suggestion);
  const texts = query.split(/[\s-_/\\|\.\,]/gm).filter(t => !!t) || [''];
  return result.replace(new RegExp('(.*?)(' + texts.join('|') + ')(.*?)','gi'), '$1<b>$2</b>$3');
},
```

**Comment by Raiondesu** [comment]
Hello, @willplaehn :)

Wow, seems like you almost nailed it with your solution! I'll definitely try it out.
It seems interesting though that the problem is only caused when there's only a single letter "b"...

P.S.
Thanks for reporting this! Can't believe I overlooked such a stupid error...
