### ISSUE TITLE
Custom Input input event is not handled

### ISSUE THREAD

**Issue by hannesaasamets** [KazanExpress/vue-simple-suggest#61]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
Custom Input input.stop="onInput" does not trigger the suggestions list to be opened. The native input's event propagation has to be limited within the Custom Input component to avoid two input events surfacing. When the custom event emits its own input event, the suggestions list is not opened.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Inside Custom Input specifying @input.stop="onInput" for the native input and then handling it on the Custom Input level as following
```
onInput (e) {
  this.$emit('input', e.target.value)
  console.log('input', e)
},
```

## **What is the expected behavior?**
The Custom Input's input event should suffice for the suggestions to appear

## **What is the motivation / use case for changing the behavior?**
This behavior the Custom Input can not be changed and there is no obvious reason to do it either.

## **Please tell us about your environment:**
  
  - Version: 1.6.0
  - Browser: Chrome 66
  - Language: ES6/7

**Comment by Raiondesu** [comment]
Hello, @hannesaasamets.
I can see the problem now: the reason of your component not working with vue-simple-suggest lies in `input.stop="..."`.

You see, vue-simple-suggest uses event bubbling to catch internal input events. So if you stop the bubbling - the event won't be triggered.

Do you absolutely have to stop input event propagation in your case?

**Comment by Raiondesu** [comment]
In current situation I see to possible in-place fixes:
1. Use `input.native.stop="..."` on `vue-simple-suggest` rather than on your custom input to stop event propagation.
2.Bind both v-models of two components to a single variable, so it would retrigger the event on its change.

**Comment by Raiondesu** [comment]
About the fixing if there issue itself - I think that your example kinda proves that event bubbling is not really that reliable of a way for internal event handling.
I'll try to come up with something else today.

**Comment by hannesaasamets** [comment]
1. Removing `.stop` from the Custom Input is not an option. 
2. Binding vue-simple-suggest & custom-input v-models to a same variable still did not trigger the suggestions list; showList() had no effect either. Was that your suggestion?

**Comment by Raiondesu** [comment]
Well, then I guess you can wait for the fix to come out **or** install a partially fixed version from a dev branch via npm - `npm install --save KazanExpress/vue-simple-suggest#dev`

**Comment by hannesaasamets** [comment]
Thank you, that seems to have worked!
Aside, I do get the following error, perhaps you can say if that is something simple-suggest component is responsible for:
```
[Vue warn]: Error in event handler for "focus": "TypeError: Cannot read property 'sourceCapabilities' of undefined"

found in

---> <BbInput> at src/components/Input/Input.vue
       <VueSimpleSuggest>
         <BbTypeahead> at src/components/typeahead/Typeahead.vue
           <Root>
