### ISSUE TITLE
Min-length for suggestions to appear

### ISSUE THREAD

**Issue by hannesaasamets** [KazanExpress/vue-simple-suggest#64]
## **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## **What is the current behavior?**
The suggestions appear after the first character has been entered to the input.

## **What is the expected behavior?**
There should be a minLength prop to specify the amount of characters entered before the suggestions trigger (0 or any positive integer). In case of _zero_ the suggestions appear as soon as the input receives focus.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
Different use cases require different approach.
Sometimes you want to query the database once the user has entered at least 2 characters.
Sometimes you want the suggestions dropdown to appear as soon as you click on the input.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.13
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all]
  - Language: [ ES6 ]

**Comment by Raiondesu** [comment]
Seems like the #34 is broken again.
