### ISSUE TITLE
Hovered with arrow Up / down

### ISSUE THREAD

**Issue by Geminii** [KazanExpress/vue-simple-suggest#67]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

Hi guys, thanks a lot for your work. 
I found a problem about hovered only with arrow up and down.
But maybe i do something wrong about my configuration ?

```
<vue-simple-suggest ref="suggestComponent"
                          v-model="selected" mode="select"
                          :max-suggestions="10"
                          :min-length="1"
                          :debounce="200"
                          :controls="{
                            selectionUp: [38, 33],
                            selectionDown: [40, 34],
                            select: [13, 36],
                            hideList: [27, 35]
                          }"
                          :list="simpleSuggestionList"
                          :placeholder="placeholder"
                          :display-attribute="'value'"
                          @select="validAutocomplete"
                          @hover="onSuggestHover"
                          @request-start="onRequestStart"
                          @request-done="onRequestDone">
        <input class="inputText" v-model="text" :placeholder="placeholder" @focus="isFocus = true" @blur="isFocus = false" :display-attribute="'count'" />

        <template slot="misc-item-above" slot-scope="{ suggestions, query }">
          <!-- Show "No result" otherwise, if not loading new ones -->
          <div class="misc-item" v-if="suggestions.length === 0 && !loading">
            <p><span>No results</span> - Bla bla bla ...</p>
          </div>
        </template>

        <div slot="suggestion-item" slot-scope="scope">
          <div class="text">
            <span>{{ scope.suggestion.value }}</span>
          </div>
          <div class="count">
            <span>{{ scope.suggestion.count }}</span>
          </div>
        </div>

        <div class="misc-item" slot="misc-item-below" slot-scope="{ suggestions }" v-if="loading">
          <span>Loading ...</span>
        </div>
      </vue-simple-suggest>
```

```
onSuggestHover(suggestion) {
        console.log('suggestion = ', suggestion.value);       
}
```

**The problem  :** 
When i use mouse to hover on suggestion, there is no bug. 
When i use nav arrow down, the value on the first and second item works but not the others. It seems to be block at second items but not with the mouse. 

Thanks for your help.
Regards,

**Comment by Raiondesu** [comment]
Hello, @Geminii!
Thank you for your report!

We already identified the source of the bug and going to fix it soon.

**Comment by Geminii** [comment]
Hi :)
@Raiondesu Thanks :)
@kaskar2008 Here is an example of my data : 
`[
   {
      "value":"Résolution de la vente",
      "count":19
   },
   {
      "value":"Usage du nom de son mari après le divorce",
      "count":10
   },
   {
      "value":"Solde locatif",
      "count":9
   },
   {
      "value":"Suspension de la clause résolutoire",
      "count":7
   },
   {
      "value":"Suspension de la procédure de saisie immobilière",
      "count":4
   },
   {
      "value":"Résiliation du bail par acquisition de la clause résolutoire",
      "count":3
   },
   {
      "value":"Résidence habituelle des enfants au domicile du père dans le cadre d'un exercice conjoint de l'autorité parentale",
      "count":1
   },
   {
      "value":"Stage de sensibilisation à la sécurité routière",
      "count":1
   },
   {
      "value":"Violation de la clause de non concurrence",
      "count":1
   },
   {
      "value":"autorisé la séquestration du mobilier",
      "count":1
   }
]`
Like you said (that i didn't understand) is to precise the `valueAttribute`. For default it's `id` so yes in my case it can't works. 

Sorry for the inconvenience, i will precise the answer of my API call.
Thanks a lot for your work and your help. 

Best regards,

**Comment by kaskar2008** [comment]
@Geminii You can add a unique attribute to each item in this list using `Array.prototype.map()` method right after the calling your API and before returning it to the vue-simple-suggest. And then add an attribute `value-attribute` to the vue-simple-suggest component. For example:
```js
async yourApiMethod() {
  let list = await fetch('your_api_call') // api call that returns a list of data
  return list.map((el, index) => ({ ...el, index }))
}
```
And in the component props:
```html
<vue-simple-suggest value-attribute="index">
...
</vue-simple-suggest>
```

**Comment by Geminii** [comment]
@kaskar2008 Thanks a lot for your precision. 
I just precise the :value-attribute="'value'" and it works :)

**Comment by kaskar2008** [comment]
@Geminii Glad to hear it :)
But I should warn you: `value-attribute` must be unique. If there is any chance that in your list field `value` will be duplicated - this bug will come up again.

**Comment by Geminii** [comment]
@kaskar2008 Thanks for the precision. I can solve it now if i got the same problem among to you :)
Thanks a lot again for your help and your work ;)

**Comment by einarjohnson** [comment]
I am experiencing a very similar problem the value-attribute is set to a uuid column so it should be unique. every time I use the keyboard arrows the hover state doesn't seem to be triggered. (mouse hovering works fine)

**Comment by Raiondesu** [comment]
Hi, @einarjohnson.
Could you please provide an example of your `uuid`s and an example of how you use the component?
