### ISSUE TITLE
IE 11 Support?

### ISSUE THREAD

**Issue by cshomo11** [KazanExpress/vue-simple-suggest#75]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

## **What is the current behavior?**
Loading the component in IE 11 results in a Syntax Error, caused by the arrow functions in the ES6.js file. I can't tell if this component is IE 11 compatible or not, if it is, am I missing an option or build step to get it back to ES2015 compliant.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
We have an application that must support IE 11 and hope to use this component.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.16
  - Vue-simple-suggest version: 1.8.0
  - Browser: IE 11
  - Language:  TypeScript 2.9.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @cshomo11.
Unfortunately, es6 arrows are not supported in any IE. Therefore you should consider using UMD or commonjs builds, which do not have arrow functions and are fully IE compatible.

**Comment by cshomo11** [comment]
We used the CommonJS build and everything worked as intended. Thanks for your help!

**Comment by panay** [comment]
Hi, I used the CommonJS build (cjs), but I have `Syntax error` in this line: `const a=t=>t.some(t=>t===e.keyCode)`

**Comment by Raiondesu** [comment]
@panay, such error is not possible if importing cjs build only.
