### ISSUE TITLE
Question: Custom filter function

### ISSUE THREAD

**Issue by BuriakPavel** [KazanExpress/vue-simple-suggest#76]
I'm newest at vue and trying to implement your autocomplete. 
Could you please to provide the example of 'customFilterFunction' that was included to docs at TLDR section:

`<vue-simple-suggest  ...
:filter="customFilterFunction"
 ... ></vue-simple-suggest>
`

and then I read:

> filter | Function | - | A custom function for filtering the suggestion results that accepts a single item and a query to filter by as its 2 arguments. Used only if filter-by-query is set to true.

but still can't understand, whats data is this function retuns or changes?

**Comment by Lofbergio** [comment]
Take a look here: https://github.com/KazanExpress/vue-simple-suggest/blob/0824efaead8241ab2290f2b59bfde246eb46c588/lib/vue-simple-suggest.vue#L108

What this function does is:
If we have a "search value" then use the lowerCase version of it to find it in displayProperty in each element. Return a boolean if the indexOf is greater than -1.
_Sidenote: the tilde character (~) is a bit of magic which im not a fan of. You can read about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_NOT_

If we dont have a "search value" then just return true or else we wont get any suggestions at all.

**Comment by Raiondesu** [comment]
@Lofbergio, thank you for resolving this.

@BuriakPavel, please, close the issue if resolved. I'll close it at weekends otherwise.

**Comment by BuriakPavel** [comment]
@Lofbergio, @Raiondesu, thank you for the answers!
