### ISSUE TITLE
Class 'hover' is added to all suggestions at once when you're using an array of objects for :list prop.

### ISSUE THREAD

**Issue by ATselikovSnp** [KazanExpress/vue-simple-suggest#78]
## **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
I'm using an array of objects for :list prop, and when i'm hovering my cursor over suggestions, or when I press up and down keys, class 'hover' added to all of the suggestions, not the only one which i'm hovering my mouse over, or selected with keyboard keys.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
<template>
   <div>
         <vue-simple-suggest
         v-model="skillName"
         :list="array">
             <div slot="suggestion-item" slot-scope="{ suggestion }">
                 {{ suggestion.a}}
             </div>
         </vue-simple-suggest>
  </div>
</template>
```
This template also gives the same problem:
```
<template>
   <div class="arbiters-catalog">
       <template>
           <div>
               <vue-simple-suggest
                       v-model="skillName"
                       :list="array"
                       display-attribute="a">
               </vue-simple-suggest>
           </div>
       </template>
   </div>
</template>
```
Script is the same for both cases.
```
<script>
    import VueSimpleSuggest from 'vue-simple-suggest';
    export default {
        components:{
            VueSimpleSuggest,
        },
        data:function(){
          return{
              skillName:'',
              array:[{a:'aa'},{a:'ab'},{a:'ac'}]
          }
        },
}
</script>
```
## **What is the expected behavior?**
It should add 'hover' class only to the selected by keyboard or hovered by cursor item.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
It's a bug, bugs are bad.

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.17
  - Vue-simple-suggest version: 1.8.0
  - Browser: [Chrome  65.0.3325.181 | Firefox 61.0.1]
  - Language: [ES6/7]

##**This is how it looks**
![2018-08-14 15-34-00 1](https://user-images.githubusercontent.com/40032061/44091884-97e2eeee-9fd7-11e8-9b18-e06176d4c758.png)
![2018-08-14 15-14-56 1](https://user-images.githubusercontent.com/40032061/44091768-3af73794-9fd7-11e8-8a9c-45fed9559a27.png)

**Comment by kaskar2008** [comment]
Hello @ATselikovSnp 
This is not a bug.
You must define a unique key for every element in array.
There are special props for that case: `display-attribute` and `value-attribute` with default values (see [Props documentation section](https://github.com/KazanExpress/vue-simple-suggest#props)). They are mandatory when using an array of objects with properties other than `id` and `title`.

**Comment by ATselikovSnp** [comment]
Thanks @kaskar2008 , now it works!
