### ISSUE TITLE
Mode 'select' showing [object Object] when clicking the suggestion.

### ISSUE THREAD

**Issue by Christhofernatalius** [KazanExpress/vue-simple-suggest#80]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

It works fine if I don't specify the v-model, but how to get the selected value without v-model?
Please help...

![2018-08-22_14-16-19](https://user-images.githubusercontent.com/13524958/44448728-44e2b680-a616-11e8-8f95-9fe41e765cc3.gif)

## This is my code
```
<template>
	<div>
		<vue-simple-suggest
			class="m-5"
			ref="suggestComponent"
			v-model="chosen"
			mode="select"
			display-attribute=name
			value-attribute=id
			:debounce=500
			:list="customerList"
			:filter-by-query="true">
		</vue-simple-suggest>
	</div>
</template>

data() {
	return {
		chosen: '',
		customerList: [
			{
				id: 1,
				name: 'John',
			},
			{
				id: 2,
				name: 'Jane',
			},
			{
				id: 3,
				name: 'July',
			},
		],
	}
},
```

### This is how I importing Vue-simple-suggest
in the main.js
```
import VueSimpleSuggest from 'vue-simple-suggest'
Vue.component('vue-simple-suggest', VueSimpleSuggest)
```

### I use 
  - Vue.js Version: 2.5.17
  - Vue-simple-suggest version: 1.8.1
  - Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by Christhofernatalius** [comment]
Oh, I got it work by adding
`<input type="text" v-model="chosen.name">`

**Comment by Christhofernatalius** [comment]
using `<input type="text" v-model="chosen.name">` makes it error if chosen is null (when clearing the textbox)
so I switched into using computed
```
chosenName: function () {
	if (this.chosen) {
		return this.chosen.name
	}
	return ''
},
```

but this will clear the text after selecting the item and pressing backspace, instead of just clearing 1 letter

**Comment by Christhofernatalius** [comment]
And I'm trying boldenSuggestion features, it throws error for me if used in mode 'select', and clicking the input again after selecting the item

`Error in render: "TypeError: query.split is not a function"`

This is because query is no longer a string, but an object.
To overcome this, I added checking typeof query in boldenSuggestion just before query.split

```
boldenSuggestion(scope) {
	if (!scope) return scope

	var { suggestion, query } = scope

	let result = this.$refs.suggestComponent.displayProperty(suggestion)

	if (!query) return result
	
	if (typeof query === 'object') {
		query = query.name
	}

	const texts = query.split(/[\s-_/\\|.]/gm).filter(t => !!t) || ['']
	return result.replace(new RegExp('(.*?)(' + texts.join('|') + ')(.*?)','gi'), '$1<b>$2</b>$3')
},
```

but it's not dynamic, because user should be able to use other attribute besides 'name'.
maybe you guys can do something about it.

**Comment by Raiondesu** [comment]
@Christhofernatalius, please, understand that the `select` mode changes how v-model works.
With the mode `select` being chosen - the `value` prop expects and object, not a string. The `@input` event also emits an object. This way, if `value` (read `v-model` value) is initially set as string - the JS will try to cast any assignable thing into a string. Thus the `[object Object]` situation.

Closing this for now.
Let us know if the problem persits upon setting the `v-model` correctly.

P.S. About `boldenSuggestion` - you hardcoded the `name` property, even though the defined property is accessible through the component reference itself. Read the docs, do your research and everything will hopefully work fine. 😃

**Comment by Christhofernatalius** [comment]
> P.S. About boldenSuggestion - you hardcoded the name property, even though the defined property is accessible through the component reference itself.

That's why I said "but it's not dynamic, because user should be able to use other attribute besides 'name'."
Already scrolling over and over the documentation for more than 4 hours.

This is how I do it in the end.
```
boldenSuggestion(scope) {
	if (!scope) return scope

	var { suggestion, query } = scope

	let result = this.$refs.suggestComponent.displayProperty(suggestion)
	let attr = this.$refs.suggestComponent.displayAttribute
	
	if (!query) return result

	if (typeof query === 'object') {
		query = query[attr]
	}

	const texts = query.split(/[\s-_/\\|.]/gm).filter(t => !!t) || ['']
	return result.replace(new RegExp('(.*?)(' + texts.join('|') + ')(.*?)','gi'), '$1<b>$2</b>$3')
},
```

**Comment by Raiondesu** [comment]
@Christhofernatalius, I really can relate to your situation.

`this.$refs.suggestComponent.displayAttribute` is dynamic enough for most cases. Even for reactive `display-attribute`.

We're trying to make this component better, more customizable and less verbose, though.

So if you'll have any suggestions on improving current situation - just let us know with an Issue or a PR. We'll be glad to respond.

:)
