### ISSUE TITLE
Using valueAttribute value in v-model?

### ISSUE THREAD

**Issue by kurbar** [KazanExpress/vue-simple-suggest#83]
Does the autosuggest component currently support using the value from an object property by defining it in valueAttribute?

For example given, an example array of objects:
```
[
  {
    "id": 1,
    "name": "Item 1"
  },
  {
    "id": 2,
    "name": "Item 2"
  }
]
```

And an example usage:
```
<autosuggest :list="getList" display-attribute="name" value-attribute="id" v-model="selectedId" />
```

If I select a suggestion, would I be able to get `selectedId` v-model to equal that of an object `id` property? Currently based on testing I wasn't able to.

**Comment by Raiondesu** [comment]
Hello, @kurbar.
No, it currently doesn't.
It does, however, support binding `v-model` to the whole object with `mode="select"`. The reason for such behavior is simple: binding the whole object provides much more flexibility in accessing its properties than binding a single attribute.

So, with `mode="select"` and `v-model="yourSelectedObject"` you can `yourSelectedObject.id` anywhere you need.

**Comment by kurbar** [comment]
@Raiondesu Hey. Sure there is no problem in actually using the object itself. It just got me questioning on what is the use case of `value-attribute`. Based on the README, it just generates a unique reference key to the object? Maybe the naming of the prop is misleading?

Anyways thank-you very much for your reply. I'll close the issue.

**Comment by Raiondesu** [comment]
@kurbar I think you're right about the name of the prop being misleading a bit.
We'll consider renaming or repurposing for the next version.
