### ISSUE TITLE
How to use filter-by-query and how to pipe the text before it reaches vue-simple-suggest?

### ISSUE THREAD

**Issue by ljm42** [KazanExpress/vue-simple-suggest#85]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

Given the simple example below:

```
<!-- Some component.vue -->
<template>
  <div>
    <vue-simple-suggest v-model="chosen" :list="simpleSuggestionList" :filter-by-query="true">
      <input type="text" v-model="chosen">
    </vue-simple-suggest>

    <br>

    <p>Chosen element: {{ chosen }}</p>
    <p v-on:click="clickme">click me</p>
  </div>
</template>

<script>
import VueSimpleSuggest from 'vue-simple-suggest'
import 'vue-simple-suggest/dist/styles.css' // Optional CSS

export default {
  components: {
    VueSimpleSuggest
  },
  data() {
    return {
      chosen: ''
    }
  },
  methods: {
    simpleSuggestionList() {
      return [
        'Vue.js',
        'React.js',
        'Angular.js'
      ]
    },
    clickme() {
      this.chosen = "js";
    }
  }
}
</script>
```

Question 1:
* Type "vue" in the input box, the dropdown shows "Vue.js"
* Click on "click me", it sets the value of the "chosen" input box to "js"
* Then click on the input box.  Note that the dropdown still shows "Vue.js" instead of the three options that contains "js". You have to actually type in the input box in order for the dropdown to update.

So... Is there a way to tell VueSimpleSuggest that the value of "chosen" has been updated, so when the user clicks the input box the correct options are displayed?

Question 2:
If you type "js" (including the quotes) into the "chosen" input box, there are no results. Is there a way intercept the query and strip the quotes before VueSimpleSuggest processes it? Note: I don't want to change the value of "chosen" , just massage it before VueSimpleSuggest looks for it in simpleSuggestionList

Thank you for any help you can provide!

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [ ] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [x] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 3.0.1
  - Vue-simple-suggest version: 1.8.2
  - Browser: [all | Chrome 68 | Firefox 62]
  - Language: [all | ES6/7 | ES5 ]

**Comment by ljm42** [comment]
First, let me say I really appreciate you taking the time to help me with this!

For question 2, I had to change:
  ~this.displayProperty(item)...
to:
  ~item...
in order to get it to work. Otherwise it would always display the entire list rather than just the items that match.

Interesting to note... this filter does not apply to the boldenSuggestion code, I needed to duplicate the quote removal code there too:
```
replace(/"/g, '')
```


For question 1, I added mode="select" but it still behaves the same... when I set the value of "chosen" via javascript, the next time you click the dropdown it still has the old values.

Here is the longer version of what I am trying to do... VueSimpleSuggest is an input box on a search form. It auto-suggests values based on a limited set of tags (although the user is welcome to search for things that are not in the dropdown too)

Off to the side, I have a list of suggested tags to help people search. When you click one of those tags, it changes the input box and issues the correct search. But the next time you click the VueSimpleSuggest search box, it shows the wrong auto-suggest values until you physically type in the box. So I'm looking for a method to call that alerts VueSimpleSuggest that the value of the inputbox has changed. 

Hopefully that is more clear :)

**Comment by Raiondesu** [comment]
Oh, with the question 1 it's simple then - you're looking for a ref method `research`!
It forces vue-simple-suggest to reevaluate the suggestion list based on the query. this way you will not need the `mode="select"`.
Also, you could `$refs.vueSuggest.select(this.chosen)`.

Do not hesitate to use the [ref API](https://github.com/KazanExpress/vue-simple-suggest#ref-methods). It can be very useful for extending and customizing the functionality of a component! 👌

As for the question 2 - my answer was just a draft anyway. Glad you managed to work out the rest of the solution. 🙂

**Comment by ljm42** [comment]
Woot! I finally got it to work by calling `research` within `setTimeout()` , but I'm open to something better if you have a way around setTimeout() :)

Here is a minimal script showing it in action:

```
<!-- Some component.vue -->
<template>
  <div>

    <p>Chosen element: {{ chosen }}</p>
    <ul>
      <li v-on:click="setChosen('vue')">Set "vue"</li>
      <li v-on:click="setChosen('react')">Set "react"</li>
      <li v-on:click="setChosen('angular')">Set "angular"</li>
      <li v-on:click="setChosen('js')">Set "js"</li>
    </ul>

    <vue-simple-suggest v-model="chosen" :list="simpleSuggestionList" :filter-by-query="true" ref="suggestComponent">
      <input type="text" v-model="chosen">
    </vue-simple-suggest>

  </div>
</template>

<script>
import VueSimpleSuggest from 'vue-simple-suggest'
import 'vue-simple-suggest/dist/styles.css' // Optional CSS

export default {
  components: {
    VueSimpleSuggest
  },
  data() {
    return {
      chosen: ''
    }
  },
  methods: {
    simpleSuggestionList() {
      return [
        'Vue.js',
        'React.js',
        'Angular.js'
      ]
    },
    setChosen(val) {
      this.chosen = val;
      setTimeout(() => {
        this.$refs.suggestComponent.research();
      }, 100);
    }
  }
}

</script>
```

If you don't mind... I've come up with a 3rd question / issue, which is when you use this code from the docs:
```
<!-- Main slot template -->
<template slot="misc-item-above" slot-scope="{ suggestions, query }">
  <div class="misc-item">
    <span>You're searching for '{{ query }}'.</span>
  </div>

  <!-- Sub-template if have any suggestions -->
  <template v-if="suggestions.length > 0">
    <div class="misc-item">
      <span>{{ suggestions.length }} suggestions are shown...</span>
    </div>
    <hr>
  </template>

  <!-- Show "No result" otherwise, if not loading new ones -->
  <div class="misc-item" v-else-if="!loading">
    <span>No results</span>
  </div>
</template>
```
the browser complains about the ` v-else-if="!loading"` section:
```
[Vue warn]: Property or method "loading" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
```

**Comment by Raiondesu** [comment]
@ljm42, `research` returns a promise, so you have to await it in some cases.
Also, there should probably be `this.$forceUpdate()` before `research()` in `setChosen() {  }`. This should help avoid timeouts.

About question 3: the example from the docs assumes that you already have the boolean `loading` variable in your component's data that you set to `true` upon starting a request and set to false upon finishing it...

**Comment by ljm42** [comment]
I would humbly suggest that the docs could use a little more detail :) Nonetheless, I really appreciate the time you took to help. And thank you for making this component in the first place, it is excellent.

**Comment by Raiondesu** [comment]
Thank you too, @ljm42, have a nice time!
😊
