### ISSUE TITLE
IE 11 compatibility

### ISSUE THREAD

**Issue by ljm42** [KazanExpress/vue-simple-suggest#86]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**

Unfortunately, I need to support IE 11.

I'm trying to get the sample app to work in Vue 3.0.1. I've read the docs, but I'm not sure how to actually get all the polyfills.  

Up until now, I've been using this import statement:
```
import VueSimpleSuggest from 'vue-simple-suggest'
```
It works great in Firefox and Chrome, but IE displays a blank screen with a syntax error pointing to a very long line starting with:
```
eval("__webpack_require__.r ...
```

I've also tried this one:
  ```
const VueSimpleSuggest = require('vue-simple-suggest/dist/cjs')
```
But it throws Vue errors, so it seems to be a step in the wrong direction:
```
  [Vue warn]: Error in created hook: "TypeError: Object doesn't support property or method 'assign'"
```

Based on what I've read elsewhere, I've specified polyfills in the babel.config.js file:
```
module.exports = {
  presets: [
    [
      "@vue/app",
      {
        polyfills: [
          "es6.promise",
          "es6.array.iterator",
          "es6.symbol",
          "es6.object.assign",
          "es6.async"
        ]
      }
    ]
  ]
};
```

and tried forcing babel to transpile dependencies in vue.config.js:
```
module.exports = {
  transpileDependencies: ["vue-simple-suggest"]
};
```
But I'm not getting anywhere.  Would you be open to going into more detail on how to get the sample app to work in IE 11 from Vue 3.0.1?

Thanks!

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 3.0.1
  - Vue-simple-suggest version: 1.8.2
  - Browser: [IE 11]
  - Language: [| ES6/7 | ES5 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
@ljm42 Hello!
Can you please try to import iife build?
const VueSimpleSuggest = require('vue-simple-suggeet/dist/iife')
It contains all the necessary polyfills (at least it should 😁)

**Comment by ljm42** [comment]
Hmm, when I swap this:
```
const VueSimpleSuggest = require('vue-simple-suggest/dist/cjs')
```
for this:
```
const VueSimpleSuggest = require('vue-simple-suggest/dist/iife')
```

I get a general JS error in all browsers:
```
ReferenceError: Vue is not defined
```

Do I need to move it to main.js somehow, where Vue is defined?


My main.js looks like this:
```
import Vue from "vue";
import App from "./App.vue";

Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");
```

App.vue is super basic:
```
<template>
  <div id="app" class="content-fluid">
    <main>
      <VueSimpleSuggest/>
    </main>
  </div>
</template>

<script>
import VueSimpleSuggest from './components/ViewSimpleSuggest.vue'

export default {
  name: 'app',
  components: {
    VueSimpleSuggest,
  }
}
</script>
```

and ViewSimpleSuggest.vue is the sample component

**Comment by Raiondesu** [comment]
Hello, @ljm42. The thing is that importing a cjs build in fact was a step in the right direction. Vue simply requested one polyfill: `Object.assign` (stated in the error message). Which you did provide later but also changed your build again, for some unknown reason.

VueSimpleSuggest [supports IE11 just fine if set up correctly](https://github.com/KazanExpress/vue-simple-suggest/issues/75).

That being said, IIFE has a different purpose, as it assumes to have Vue in global window scope (which is not true in your case).
Your current build with force-transpilation of the component should work just fine. Just read error messages carefully and you'll get it done. 😉
