### ISSUE TITLE
Custom `input` bound to `v-model` doesn't respect selection changes.

### ISSUE THREAD

**Issue by humblecoder** [KazanExpress/vue-simple-suggest#87]
## **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request

## **What is the current behavior?**
Inserting a custom `<input>` allows me to format, and set specific values such as `required` for validation.  However, there becomes a conflict with `v-model` such that it doesn't respect manual changes.  The "suggestion" box pops up correctly, however, when a value is selected, the pre-existing value remains firmly.  This problem, of course, goes away, if there is no custom `<input>`

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
               <vue-simple-suggest
                  :styles="autoCompleteStyle"
                  :list="arrayStateProvince"
                  :filter-by-query="true"
                  v-model="project.state_province"
                >
                  <!-- <input class="form-control" v-validate="'required'" required> -->
                </vue-simple-suggest>
```
Without `v-model` on `input`, it won't display the initial value when the form is loaded from the data source.  If I add `v-model="project.state_province` to the custom `<input>` instance, when the form loads from the data source it fills correctly, but I can never change it.  Yes the suggestions still pop up (I'm guessing because that functionality is independent), but when I select one it "flickers" and goes back to the original value.

## **What is the expected behavior?**
How do I fully customize `<input>` while still allowing it to behave as "normal" and respect `v-model`?

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

I'm importing it globally in `main.js` though as a component.  It seems to work in all cases except where I need to fully customize `input`.

## **What is the motivation / use case for changing the behavior?**

In this particular case, I simply want the ability to `validate` and `require` the input values natively.

## **Please tell us about your environment:**
  
  - Vue.js Version: 3.0.0-beta.15
  - Vue-simple-suggest version: 1.8.2
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [ES6/7 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Raiondesu** [comment]
Hello, @humblecoder.
The issue seems to be connected with the way Vue deals with data bindings. Are you able to reproduce the issue via github-repo/jsfiddle/etc?

**Comment by humblecoder** [comment]
@Raiondesu I'm not sure what happened, but I `rm -rf node_modules`, reinstalled and the problem seems to have resolved itself.  Closing for now, but will re-open if I can nail down the specific  issue. Thanks.

**Comment by Raiondesu** [comment]
@humblecoder, I'm glad the issue disappeared.
