### ISSUE TITLE
UglifyJS error when building for `production`

### ISSUE THREAD

**Issue by humblecoder** [KazanExpress/vue-simple-suggest#88]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
With my basic `laravel-mix`-based `webpack.config` I use `uglify` to build the application for production.  All other non-uglify build methods work without a hitch.  However, now that I've added `vue-simple-suggest` to the application, when running `yarn run production` (which tries to uglify) I receive the following:

```
/js/main.js from UglifyJs
Invalid assignment [./node_modules/vue-simple-suggest/dist/es6.js:15,0][/js/main.js:229346,39]
```

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

`yarn run production`

## **What is the expected behavior?**
Build and uglify/minify without throwing an error.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**
I'd like to be able to minify without issue.  I've upgraded all relevant packages, to no avail.

## **Please tell us about your environment:**
  
  - Vue.js Version: 3.0.0-beta.15
  - Vue-simple-suggest version: 1.8.2
  - Browser: [N/A]
  - Language: [ES6/7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment]
Hello @humblecoder 
I guess this issue is related to [this one](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/187). Can you check it out and if it's not your case - reveal your webpack version and config please?

**Comment by humblecoder** [comment]
Adjusting my config file to the "node_module" `laravel-mix` `webpack.config.js` file and updating ***to*** the following seems to have done the trick:
```
    "uglify-js": "^3.4.9",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "laravel-mix": "^2.1.0",
```

🤷‍♂️

**Comment by gurungabish16** [comment]
Hello @humblecoder  Greetings!
I also got stuck in this issue while building it and i would like to know if you got the solution for it or not?
Thanks!
