### ISSUE TITLE
Can't select items with arrow up/down keys when suggestion list has scrolled content

### ISSUE THREAD

**Issue by jcarrera** [KazanExpress/vue-simple-suggest#89]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

I have a large number of suggestions and have set a max-height with overflow:hidden to the suggestions overlay. So at the moment only 5 suggestions are shown but with the mousepad the user can scroll the overlay list and select any option. 

The user can't use the arrow up/down keys though to select items not in view. 

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I used your demo example on the site. I added additional data to the list. I set a max-height of 100px and set overflow:hidden on the "suggestions" element. This creates scrolled content in the overlay. 

Now type a letter to see the overlay with results. Start pressing the down arrow and notice the list does not scroll and items not currently in view remain hidden.

## **What is the expected behavior?**

I'd expect the list to scroll when hovering/focusing on an item not visible in the list with the arrow up/down keys.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **What is the motivation / use case for changing the behavior?**

Accessibility and allowing folks to use standard/common keyboard commands to interact with an auto-complete component. 

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.16
  - Nuxt 2.0
  - Vue-simple-suggest version: 1.8.2
  - Browser: [ Chrome latest | Firefox latest | IE 11 | Safari latest | Mobile Chrome | iPhone 6+ ]
  - Language: ES6/7

**Comment by Raiondesu** [comment]
Hello, @jcarrera.
To clarify that we understood the problem correctly - could you please provide a reproduction repo (perhaps with a fork of vue-simple-suggest) or something?

**Comment by Raiondesu** [comment]
Hello, @jcarrera.
Unfortunately, the feature you're talking about does not rest within vue-simple-suggest's responsibilities and can be classified as custom behaviour because there are many varieties of possible behaviours for suggestions scrolling.

Even though the behaviour you request is pretty much standard, we think you could still easily implement this yourself using the [controls](https://github.com/KazanExpress/vue-simple-suggest#default-controls) prop.

**Comment by panay** [comment]
Hi, @Raiondesu 
I think that it should be included in this plugin? If you change the default browser behavior, then you should make it is work.
