### ISSUE TITLE
"event" variable should be instantiated for every component instance

### ISSUE THREAD

**Issue by petyunchik** [KazanExpress/vue-simple-suggest#92]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**

All instances of the component are using same component-wide variable `event`:
https://github.com/KazanExpress/vue-simple-suggest/blob/3c5e5fa883d14307fb11fddff47ca47e49a665b5/lib/vue-simple-suggest.vue#L59

It should not be so, because if you instantiate multiple components with different "mode" options, every instance will override this variable for all other instances.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Instantinate two instances of the component inside the page - first in select-mode, second in input-mode and select-mode component will work as input-mode.

**Comment by Raiondesu** [comment]
Oh, that's a nice point!
I think we'll figure something out on this part today.
