### ISSUE TITLE
IE11 Bug since 1.8.1

### ISSUE THREAD

**Issue by MrWook** [KazanExpress/vue-simple-suggest#95]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
If you are using this library with the IE11 a script error occures.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just use the newest version with the IE11

## **What is the expected behavior?**
Script should not fail.

### How are you importing Vue-simple-suggest?

- [x] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`) 
With own babel compilation

## **What is the motivation / use case for changing the behavior?**
The IE11 should be supported. Atleast if there aren't any major changes. 

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.17
  - Vue-simple-suggest version: 1.8.2
  - Browser: [all]
  - Language: [ES6/7]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Since 1.8.1, which is not tagged inside this github repo but is on NPM, the IE isn't supported anymore because you are using `$el.closest()` inside the `prepareEventHandlers()` method. 
The function `closest()` is not supported in IE11.
The codesnipped comes from this PR #79

**Comment by kaskar2008** [comment]
Thank you @MrWook for reporting.
We will resolve this in the next patch :)

**Comment by kaskar2008** [comment]
Fixed in version 1.8.3.
Optional polyfills (see more [here](https://github.com/KazanExpress/vue-simple-suggest#polyfills))
