### ISSUE TITLE
Multiple suggestions that do not overwrite previous suggestion

### ISSUE THREAD

**Issue by vmihailenco** [KazanExpress/vue-simple-suggest#98]
Assuming suggestion list is ["Vue", "React", "Angular"] is it possible to achieve following behavior:
- user types "V" and selects "Vue" - the selected value is "Vue"
- user types " R" and selects "React" - the selected value is "Vue React"
- user types " A" and selects "Angular" - the selected value is "Vue React Angular"

I've spent few hours replacing `v-model` with `:value` and `@input`, tried `mode="select"` but without much luck. As I chose next suggestion the previous suggestion is overwritten even though I specify `:input` that does not change at all. Is it possible with vue-simple-suggest? Any hints are appreciated.

PS Sorry for creating an issue to ask a question

**Comment by Raiondesu** [comment]
@vmihailenco , I'm afraid that vue-simple-suggest alone wouldn't cut it. It's a simple single-purpose component.

What you need - is to combine vue-simple-suggest with a tag input or a multi-selection input component.

**Comment by vmihailenco** [comment]
I already use multiselect to create tags based filters, but I wanted to experiment with building something more lightweight using simple input field and pseudo tags like "author:vmihailenco closed:true". Basically how Github/Slack search works but with autosuggestion. If you can recommend any libs to achieve that - thanks in advance.
